// CNSBudgetEngine.swift — PR 10C of the weekly-coach roadmap: hybrid CNS
// budgeting.
//
// Lifting and hard sport both draw on the same central-nervous-system
// budget. The planner's shape queues can produce three heavy days in a
// row (lift+lift+lift, or lift+hard-sport+lift) whenever overrides, sport
// logs, or the arc demotion reshuffle the week — and the user pays for
// that with a mid-week crash.
//
// This engine reads the FINISHED plan (after shape placement, overrides,
// taper, and the auto-arc) and demotes the least-needed day of any 3+
// consecutive high-CNS run. Pure logic — no persistence, no stores.
//
// Spec: PLAN-weekly-coach.md §6.3. "May require reordering planned days,
// not just trimming volume" — the demotion IS the reorder's simplest
// honest form: it removes load the user would otherwise stack.
//
// Protected days are never demoted: user-booked events/sport days carry
// fixed outside-the-app commitments. A lift day generated by the planner
// is always the expendable one.

import Foundation

enum CNSBudgetEngine {

    /// How much central fatigue a planned day draws. Lift = high (barbell
    /// work at prescription intensity); hard event/sport = high; moderate
    /// sport = moderate; rest = none.
    static func cnsCost(of day: DayPlan) -> Int {
        switch day.kind {
        case .lift: return 2
        case .event: return 2 // races/hard events read as high-CNS
        case .sport: return 1 // moderate sessions; hard ones only in logs
        case .rest:  return 0
        }
    }

    /// High-CNS threshold. A day at or above this counts toward a
    /// consecutive run.
    static let highCNSCost = 2

    /// Longest allowed consecutive high-CNS run.
    static let maxConsecutiveHigh = 2

    /// True when the plan violates the budget (any 3+ high-CNS run).
    /// Diagnostic surface — the transform below fixes it; this lets
    /// tests and callers check without mutating.
    static func violates(_ plan: WeekPlan) -> Bool {
        longestHighRun(plan.days) > maxConsecutiveHigh
    }

    /// Demote days until no 3+ consecutive high-CNS run remains.
    ///
    /// Spec §6.3: "may require reordering planned days, not just trimming
    /// volume." Two moves, in priority order:
    ///   1. RELOCATE — move a lift day out of the violating run to a rest
    ///      slot that breaks the run, preserving the user's lift-day count.
    ///      Tried first: demotion costs the user a training day; a reorder
    ///      doesn't.
    ///   2. DEMOTE — when no relocation fixes the run (sport/event days are
    ///      immovable, and every candidate landing spot still leaves a run),
    ///      demote the run's middle lift to a Recovery rest day.
    ///
    /// Repeat until clean or until nothing is actionable (guarantees
    /// termination: each iteration either relocates into a strictly
    /// shorter max-run configuration or removes a lift).
    static func balance(plan: WeekPlan) -> WeekPlan {
        var out = plan
        var guardCounter = 0
        while guardCounter < 7 {
            guardCounter += 1
            if let relocation = relocationCandidate(out.days) {
                out.days.swapAt(relocation.from, relocation.to)
                if !violates(out) { continue }  // relocation fixed it
                out.days.swapAt(relocation.from, relocation.to)  // undo, try demotion
            }
            guard let target = demotionCandidate(out.days) else { break }
            out.days[target] = DayPlan(
                date: out.days[target].date,
                kind: .rest,
                title: "Recovery",
                generatedReason: "Recovery day — balanced against your harder days"
            )
        }
        return out
    }

    /// A (from, to) pair: moving the lift at `from` (inside a violating
    /// run) to the rest slot at `to` clears the violation, preserving the
    /// user's lift-day count. Tries every (run-lift, rest) combination;
    /// nil when no single relocation fixes it.
    static func relocationCandidate(_ days: [DayPlan]) -> (from: Int, to: Int)? {
        guard let run = firstViolatingRun(days) else { return nil }
        let liftIdxs = run.filter { days[$0].kind == .lift }
        let restIdxs = days.indices.filter { days[$0].kind == .rest }
        for from in liftIdxs {
            for to in restIdxs {
                var trial = days
                trial.swapAt(from, to)
                let trialPlan = WeekPlan(days: trial, generatedAt: Date(), inputsHash: "cns-probe")
                if !violates(trialPlan) { return (from, to) }
            }
        }
        return nil
    }

    /// The index to demote next, or nil when no violating run has a
    /// demotable (lift) day. Scans for the first violating run, then
    /// picks its middle lift day (falls back to any lift in the run).
    static func demotionCandidate(_ days: [DayPlan]) -> Int? {
        let run = firstViolatingRun(days)
        guard let run, run.count >= 3 else { return nil }
        let liftIdxs = run.filter { days[$0].kind == .lift }
        guard let middle = liftIdxs.middle else { return nil }
        return middle
    }

    /// Indices of the first run of ≥3 consecutive high-CNS days, or nil.
    static func firstViolatingRun(_ days: [DayPlan]) -> [Int]? {
        var run: [Int] = []
        for (i, day) in days.enumerated() {
            if cnsCost(of: day) >= highCNSCost {
                run.append(i)
            } else {
                if run.count > maxConsecutiveHigh { return run }
                run = []
            }
        }
        return run.count > maxConsecutiveHigh ? run : nil
    }

    private static func longestHighRun(_ days: [DayPlan]) -> Int {
        var bestRun = 0
        var current = 0
        for day in days {
            if cnsCost(of: day) >= highCNSCost {
                current += 1
                bestRun = max(bestRun, current)
            } else {
                current = 0
            }
        }
        return bestRun
    }
}

private extension Array where Element == Int {
    /// Middle element (lower-middle for even counts).
    var middle: Int? {
        guard !isEmpty else { return nil }
        return self[count / 2]
    }
}
