// WeekPlan.swift — the user-facing 7-day plan.
//
// Generated by Planner.generate(memory:routines:today:) and persisted by
// PlanStore. The shape mirrors the spec in PLAN-coach-prereqs.md:
//
//   WeekPlan { days[7], generatedAt, inputsHash }
//   DayPlan  { id, date, kind, title, routineId?, sport?, protected, notes?,
//              generatedReason? }
//
// Phase 11 introduces PlanEdit operations that mutate WeekPlan via PlanStore;
// for now this is read-only (other than full regeneration on weekly check-in
// or onboarding).
//
// Dates are encoded as secondsSince1970 to match SessionStore + MemoryStore.

import Foundation

// MARK: - DayKind

enum DayKind: String, Codable, CaseIterable {
    case lift, sport, mobility, rest, event

    /// Short label rendered in the Week tab badge.
    var label: String {
        switch self {
        case .lift:     return "LIFT"
        case .sport:    return "SPORT"
        case .mobility: return "MOBILITY"
        case .rest:     return "REST"
        case .event:    return "EVENT"
        }
    }

    /// Loose grouping used by Today's hero card to pick a copy treatment.
    var isWorkout: Bool {
        switch self {
        case .lift, .mobility: return true
        case .sport, .rest, .event: return false
        }
    }
}

// MARK: - DayPlan

struct DayPlan: Codable, Identifiable, Hashable {
    var id: UUID = UUID()
    /// Start-of-day (Calendar.startOfDay) — the planner normalizes before stamping.
    var date: Date
    var kind: DayKind
    var title: String
    /// coach.db routine id when kind == .lift / .mobility. nil otherwise.
    var routineId: Int?
    /// Sport for kind == .sport days; nil otherwise.
    var sport: Sport?
    /// User-locked day (Phase 11 protectDay edit) — planner will not auto-move.
    var protected: Bool = false
    var notes: String?
    /// Human-readable rule trace ("4-day plan, day 2 → strength").
    var generatedReason: String?
}

// MARK: - WeekPlan

struct WeekPlan: Codable, Hashable {
    /// Exactly 7 days, contiguous from `days.first.date`.
    var days: [DayPlan]
    var generatedAt: Date
    /// Stable hash of the TrainingMemory inputs that produced this plan.
    /// PlanStore compares against the live memory hash to know when to regenerate.
    var inputsHash: String
}

// MARK: - Convenience

extension WeekPlan {
    /// Today's plan, or nil if today's date isn't in the window. Compares by
    /// startOfDay so it's robust across timezones / clock skew within the day.
    func today(now: Date = Date(), calendar: Calendar = .current) -> DayPlan? {
        let target = calendar.startOfDay(for: now)
        return days.first { calendar.isDate($0.date, inSameDayAs: target) }
    }

    /// Compact human label: "Mon — Sun" or "May 14–20".
    var rangeLabel: String {
        guard let first = days.first?.date, let last = days.last?.date else { return "" }
        let f = DateFormatter()
        f.dateFormat = "MMM d"
        return "\(f.string(from: first))–\(f.string(from: last))"
    }
}

// MARK: - Stable input hash
//
// Used by Planner to fingerprint the (TrainingMemory) inputs that produced
// a plan. Stable across runs (no Hashable.hashValue use — that's randomized
// per-launch in Swift). Folds a short canonical string into UInt64 (djb2)
// then base-36-encodes for compactness.

extension TrainingMemory {
    var planInputsHash: String {
        let canonical = [
            "v\(schemaVersion)",
            "ps:\(primarySport?.slug ?? "_")",
            "sp:\(sports.map(\.slug).sorted().joined(separator: ","))",
            "fc:\(primaryFocus.rawValue)",
            "se:\(season.rawValue)",
            "dy:\(availableDays.map(\.rawValue).sorted().map(String.init).joined(separator: ","))",
            "fx:\(fixedSportDays.keys.sorted { $0.rawValue < $1.rawValue }.map { "\($0.rawValue):\(fixedSportDays[$0]?.slug ?? "")" }.joined(separator: ","))",
            "mn:\(sessionMinutes)",
            "eq:\(equipment.map(\.rawValue).sorted().joined(separator: ","))",
            "ex:\(experience.rawValue)"
        ].joined(separator: "|")
        var hash: UInt64 = 5381
        for byte in canonical.utf8 {
            hash = (hash &* 33) &+ UInt64(byte)
        }
        return String(hash, radix: 36)
    }
}

// MARK: - Sample plan (preview / tests)

extension WeekPlan {
    /// Deterministic sample for previews + tests. Mon=lift, Tue=sport,
    /// Wed=mobility, Thu=lift, Fri=rest, Sat=sport, Sun=rest.
    static func sample(startingAt date: Date = Date()) -> WeekPlan {
        let cal = Calendar.current
        let start = cal.startOfDay(for: date)
        let kinds: [DayKind] = [.lift, .sport, .mobility, .lift, .rest, .sport, .rest]
        let titles = ["Push & Pull", "Climb session", "Hip mobility", "Lower body", "Rest", "Trail run", "Rest"]
        let days: [DayPlan] = (0..<7).map { i in
            DayPlan(
                date: cal.date(byAdding: .day, value: i, to: start) ?? start,
                kind: kinds[i],
                title: titles[i],
                routineId: kinds[i].isWorkout ? 1 : nil,
                sport: kinds[i] == .sport ? Sport.catalog.first(where: { $0.slug == "climbing" }) : nil,
                generatedReason: "sample data"
            )
        }
        return WeekPlan(days: days, generatedAt: Date(), inputsHash: "sample")
    }
}
