// WeekPlan.swift — the user-facing 7-day plan.
//
// Generated by Planner.generate(memory:routines:today:) and persisted by
// PlanStore. The shape mirrors the spec in PLAN-coach-prereqs.md:
//
//   WeekPlan { days[7], generatedAt, inputsHash }
//   DayPlan  { id, date, kind, title, routineId?, sport?, protected, notes?,
//              generatedReason? }
//
// Phase 11 introduces PlanEdit operations that mutate WeekPlan via PlanStore;
// for now this is read-only (other than full regeneration on weekly check-in
// or onboarding).
//
// Dates are encoded as secondsSince1970 to match SessionStore + MemoryStore.

import Foundation

// MARK: - DayKind

enum DayKind: String, Codable, CaseIterable {
    case lift, sport, rest, event

    /// Short label rendered in the Week tab badge.
    var label: String {
        switch self {
        case .lift:  return "LIFT"
        case .sport: return "SPORT"
        case .rest:  return "REST"
        case .event: return "EVENT"
        }
    }

    /// Loose grouping used by Today's hero card to pick a copy treatment.
    var isWorkout: Bool {
        switch self {
        case .lift: return true
        case .sport, .rest, .event: return false
        }
    }

    /// Pre-cleanup builds had a `.mobility` case driven by a prehab/mobility
    /// catalog that no longer exists. Saved plans from those builds may still
    /// carry `"mobility"` as the raw value — silently rewrite it to `.rest` on
    /// decode so the plan keeps loading. Active recovery is now self-directed.
    init(from decoder: Decoder) throws {
        let raw = try decoder.singleValueContainer().decode(String.self)
        if raw == "mobility" {
            self = .rest
        } else if let v = DayKind(rawValue: raw) {
            self = v
        } else {
            throw DecodingError.dataCorruptedError(in: try decoder.singleValueContainer(),
                                                   debugDescription: "Unknown DayKind: \(raw)")
        }
    }
}

// MARK: - DayPlan

struct DayPlan: Codable, Identifiable, Hashable {
    var id: UUID = UUID()
    /// Start-of-day (Calendar.startOfDay) — the planner normalizes before stamping.
    var date: Date
    var kind: DayKind
    var title: String
    /// coach.db routine id when kind == .lift AND the slot was satisfied by
    /// an explicit user-picked routine (day override). nil for generated
    /// workouts — those carry exercises directly in `generatedWorkout`.
    var routineId: Int?
    /// Workout assembled exercise-by-exercise from the user's demographic
    /// profile + movement-pattern recipes. Replaces routineId as the primary
    /// source for lift days. nil for non-workout days or for days whose slot
    /// was overridden by a routineId pick.
    var generatedWorkout: GeneratedWorkout?
    /// Sport for kind == .sport days; nil otherwise.
    var sport: Sport?
    /// User-locked day (Phase 11 protectDay edit) — planner will not auto-move.
    var protected: Bool = false
    var notes: String?
    /// Override session length in minutes; nil = use TrainingMemory.sessionMinutes.
    /// Set by the Phase 11 PlanEdit.shorten op.
    var durationMinutes: Int?
    /// Human-readable rule trace ("4-day plan, day 2 → strength").
    var generatedReason: String?
}

// MARK: - GeneratedWorkout
//
// A workout that the app composed itself from individual coach.db exercises,
// shaped by the user's DemographicProfile + a movement-pattern recipe.
// Bundled routines are still browsable in the library as inspiration / custom
// overrides — they're just no longer the primary content of a planned day.

struct GeneratedWorkout: Codable, Hashable {
    /// Display title — "Push day", "Full body A", "Mobility flow".
    var title: String
    /// One-line summary for the card view: "5 movements · ~45 min".
    var summary: String
    var exercises: [GeneratedExercise]
    var estimatedMinutes: Int
    /// Sentence used in the Today / Week explanation chips — explains *why*
    /// this workout looks the way it does ("Intermediate · push/pull/legs
    /// rotation, day 1 of 3").
    var provenance: String
    /// Build 98 — set when the LLM has refined this workout. nil = the
    /// deterministic baseline; non-nil = LLM polished on that date.
    /// Used to skip re-refining + surface "your coach personalized this"
    /// hints in future UI passes.
    var refinedByLLMAt: Date? = nil
}

/// Why this exercise ended up in the workout. Default is `.recipe` — the
/// pattern-slot recipe placed it. `.prehab` means the generator pulled it
/// from `exercise_injury_relevance` for the named injury. Coach context
/// annotates `.prehab` picks with the injury's human-readable name so the
/// LLM can explain the choice without joining tables itself.
enum ExercisePickSource: Codable, Hashable {
    case recipe
    case prehab(injurySlug: String)
}

/// One warm-up set entry — N reps at a percent of the picked exercise's
/// working weight, with rest before the next set. Synthesized by
/// WorkoutGenerator for compound primary lifts when the prime mover isn't
/// sore. EvalRigExporter passes these through to the eval-rig schema's
/// warm_up_sets array so the rubric's Q1 (ramp-set check) has a signal.
struct WarmUpSet: Codable, Hashable {
    var reps: Int
    /// e.g. 40, 60, 80 — relative to the first working set's load.
    var loadPctOfWorking: Int
    var restSeconds: Int
}

struct GeneratedExercise: Codable, Hashable, Identifiable {
    // Build 70 — coaching prescription depth.
    //
    // `rpe` is a target effort range like "7-8" or a single number "9".
    // Maps directly to "leave N reps in reserve" semantics — the coach's
    // strongest intensity cue beyond just sets × reps × rest. Nil = no hint
    // (mobility flows, or focuses where RPE doesn't apply).
    //
    // `tempo` is the eccentric/pause/concentric/pause pattern as a 4-digit
    // string like "3-1-1-0" (3s lowering, 1s bottom hold, 1s up, no top
    // hold) or "X-0-X-0" for explosive. Nil = no tempo cue.
    /// Stable id derived from (planInputsHash, slotIndex, exerciseId) — must
    /// NOT use UUID() so the same memory + slot yields the same id across
    /// regenerations (the inputs-hash drift check relies on stable plans).
    var id: String
    /// coach.db exercises.id — used to fetch full detail / find substitutes.
    var exerciseId: Int
    var name: String
    /// movement_patterns.slug the slot was filled from — for the "why this
    /// exercise" hint and grouping in the UI.
    var pattern: String?
    var isCompound: Bool
    var sets: Int
    /// Free-form reps string ("5", "8-10", "AMRAP", "30s hold"). Bridged
    /// to Int via leading-digit parsing for ActiveSession's targetReps.
    var reps: String
    var restSeconds: Int
    var notes: String?
    /// Target effort range — "7-8", "9", "7-9". Nil = no RPE cue.
    var rpe: String?
    /// 4-digit tempo string — "3-1-1-0" or "X-0-X-0". Nil = no tempo cue.
    var tempo: String?
    /// Why this exercise got picked. Defaults to .recipe so existing decoders
    /// don't need to write the field.
    var source: ExercisePickSource = .recipe
    /// Optional warm-up ramp sets BELOW working weight. Synthesized by the
    /// generator for compound primary lifts where the muscle isn't sore
    /// (eval-rig rubric Q1 — "first compound press has a ramp set listed
    /// below working weight"). Empty / nil = no ramp prescribed.
    var warmUpSets: [WarmUpSet]? = nil

    enum CodingKeys: String, CodingKey {
        case id, exerciseId, name, pattern, isCompound, sets, reps
        case restSeconds, notes, rpe, tempo, source, warmUpSets
    }

    init(id: String, exerciseId: Int, name: String, pattern: String? = nil,
         isCompound: Bool, sets: Int, reps: String, restSeconds: Int,
         notes: String? = nil, rpe: String? = nil, tempo: String? = nil,
         source: ExercisePickSource = .recipe,
         warmUpSets: [WarmUpSet]? = nil) {
        self.id = id; self.exerciseId = exerciseId; self.name = name
        self.pattern = pattern; self.isCompound = isCompound
        self.sets = sets; self.reps = reps; self.restSeconds = restSeconds
        self.notes = notes; self.rpe = rpe; self.tempo = tempo
        self.source = source
        self.warmUpSets = warmUpSets
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decode(String.self, forKey: .id)
        self.exerciseId = try c.decode(Int.self, forKey: .exerciseId)
        self.name = try c.decode(String.self, forKey: .name)
        self.pattern = (try? c.decodeIfPresent(String.self, forKey: .pattern)) ?? nil
        self.isCompound = (try? c.decode(Bool.self, forKey: .isCompound)) ?? false
        self.sets = (try? c.decode(Int.self, forKey: .sets)) ?? 3
        self.reps = (try? c.decode(String.self, forKey: .reps)) ?? ""
        self.restSeconds = (try? c.decode(Int.self, forKey: .restSeconds)) ?? 60
        self.notes = (try? c.decodeIfPresent(String.self, forKey: .notes)) ?? nil
        self.rpe = (try? c.decodeIfPresent(String.self, forKey: .rpe)) ?? nil
        self.tempo = (try? c.decodeIfPresent(String.self, forKey: .tempo)) ?? nil
        self.source = (try? c.decode(ExercisePickSource.self, forKey: .source)) ?? .recipe
        self.warmUpSets = (try? c.decodeIfPresent([WarmUpSet].self, forKey: .warmUpSets)) ?? nil
    }
}

extension GeneratedWorkout {
    /// Composition-based templateId so two generated workouts with the
    /// same exercises share a template id and the SessionStore's
    /// getPreviousSession lookup pulls forward last week's weights even
    /// when the day was regenerated (different DayPlan UUID, same exercise
    /// composition).
    var stableTemplateId: String {
        let signature = exercises.map { String($0.exerciseId) }.joined(separator: ",")
        var hash: UInt64 = 5381
        for byte in signature.utf8 { hash = (hash &* 33) &+ UInt64(byte) }
        return "gen-\(String(hash, radix: 36))"
    }

    /// Bridge to the existing WorkoutTemplate -> ActiveSession runtime so the
    /// log screen + history don't need to learn a new model.
    func toWorkoutTemplate(id: String) -> WorkoutTemplate {
        // Classify up front so reps-only movements (bird dog, dead bug, ...)
        // log as bodyweight and the LogScreen hides their weight input.
        let categories = CoachDatabase.shared.equipmentCategory(
            forExerciseIds: Set(exercises.map(\.exerciseId)))
        return WorkoutTemplate(
            id: id,
            name: title,
            category: "Generated",
            exercises: exercises.map { gex in
                ExerciseTemplate(
                    id: "gex-\(gex.id)",
                    name: gex.name,
                    type: nil,
                    unit: LoggedExercise.unit(for: categories[gex.exerciseId]),
                    targetSets: gex.sets,
                    targetReps: Self.parseRepsLeading(gex.reps) ?? 8,
                    rest: gex.restSeconds,
                    rpe: gex.rpe,
                    tempo: gex.tempo
                )
            }
        )
    }

    private static func parseRepsLeading(_ s: String) -> Int? {
        let digits = s.prefix(while: { $0.isNumber })
        return Int(digits)
    }
}

// MARK: - WeekPlan

struct WeekPlan: Codable, Hashable {
    /// Exactly 7 days, contiguous from `days.first.date`.
    var days: [DayPlan]
    var generatedAt: Date
    /// Stable hash of the TrainingMemory inputs that produced this plan.
    /// PlanStore compares against the live memory hash to know when to regenerate.
    var inputsHash: String
}

// MARK: - Convenience

extension WeekPlan {
    /// Today's plan, or nil if today's date isn't in the window. Compares by
    /// startOfDay so it's robust across timezones / clock skew within the day.
    func today(now: Date = Date(), calendar: Calendar = .current) -> DayPlan? {
        let target = calendar.startOfDay(for: now)
        return days.first { calendar.isDate($0.date, inSameDayAs: target) }
    }

    /// Compact human label: "Mon — Sun" or "May 14–20".
    var rangeLabel: String {
        guard let first = days.first?.date, let last = days.last?.date else { return "" }
        let f = DateFormatter()
        f.dateFormat = "MMM d"
        return "\(f.string(from: first))–\(f.string(from: last))"
    }
}

// MARK: - Stable input hash
//
// Used by Planner to fingerprint the (TrainingMemory) inputs that produced
// a plan. Stable across runs (no Hashable.hashValue use — that's randomized
// per-launch in Swift). Folds a short canonical string into UInt64 (djb2)
// then base-36-encodes for compactness.

extension TrainingMemory {
    /// Fingerprint of the inputs the planner reads. Build 75: now includes
    /// age (used by the planner's recovery + set-count clamps), dislikes
    /// (SQL keyword exclude), constraints (injury contraindications), and
    /// startingState (LLM coach signal). Without these in the hash, the
    /// auto-regen subscription on PlanStore deduped legitimate profile
    /// changes — editing "dislikes burpees" silently did nothing.
    ///
    /// Build 87: userInjuries (slug + severity + side) too — editing a
    /// severity should refresh the prehab-aware mobility day even if the
    /// contraindication filter result is unchanged.
    ///
    /// Skipped intentionally: height / weight / gender — they don't shape
    /// deterministic plan generation, only display + coach context. We don't
    /// want a weight log to retrigger a week-wide regen.
    var planInputsHash: String {
        let seasons = seasonsBySport
            .sorted { $0.key.slug < $1.key.slug }
            .map { "\($0.key.slug):\($0.value.rawValue)" }
            .joined(separator: ",")
        let injuries = userInjuries
            .sorted { $0.slug < $1.slug }
            .map { "\($0.slug):\($0.severity?.rawValue ?? "_"):\($0.side?.rawValue ?? "_")" }
            .joined(separator: ",")
        let canonical = [
            "v\(schemaVersion)",
            "ps:\(primarySport?.slug ?? "_")",
            "sp:\(sports.map(\.slug).sorted().joined(separator: ","))",
            "fc:\(focuses.map(\.rawValue).joined(separator: ","))",
            "ds:\(defaultSeason.rawValue)",
            "ss:\(seasons)",
            "pd:\(peakDate.map { String(Int($0.timeIntervalSince1970)) } ?? "_")",
            "mn:\(sessionMinutes)",
            "ld:\(liftDaysPerWeek)",
            "eq:\(equipment.map(\.rawValue).sorted().joined(separator: ","))",
            "ex:\(experience.rawValue)",
            "ag:\(age.map(String.init) ?? "_")",
            "dl:\(dislikes.map { $0.lowercased() }.sorted().joined(separator: ","))",
            "cn:\(constraints.sorted().joined(separator: ","))",
            "ui:\(injuries)",
            "st:\(startingState.rawValue)",
            // Phase-1 era affinity. Either the user's explicit override
            // OR the derived cohort from age (which is already in via
            // `ag:`, but the resolution table can shift independently —
            // including the resolved-or-explicit override here so the
            // plan regenerates when the user changes their pick).
            "er:\(eraOverride ?? "_")",
        ].joined(separator: "|")
        var hash: UInt64 = 5381
        for byte in canonical.utf8 {
            hash = (hash &* 33) &+ UInt64(byte)
        }
        return String(hash, radix: 36)
    }
}

// MARK: - Sample plan (preview / tests)

extension WeekPlan {
    /// Deterministic sample for previews + tests. Mon=lift, Tue=sport,
    /// Wed=rest, Thu=lift, Fri=rest, Sat=sport, Sun=rest.
    static func sample(startingAt date: Date = Date()) -> WeekPlan {
        let cal = Calendar.current
        let start = cal.startOfDay(for: date)
        let kinds: [DayKind] = [.lift, .sport, .rest, .lift, .rest, .sport, .rest]
        let titles = ["Push & Pull", "Climb session", "Rest", "Lower body", "Rest", "Trail run", "Rest"]
        let days: [DayPlan] = (0..<7).map { i in
            DayPlan(
                date: cal.date(byAdding: .day, value: i, to: start) ?? start,
                kind: kinds[i],
                title: titles[i],
                routineId: kinds[i].isWorkout ? 1 : nil,
                sport: kinds[i] == .sport ? Sport.catalog.first(where: { $0.slug == "climbing" }) : nil,
                generatedReason: "sample data"
            )
        }
        return WeekPlan(days: days, generatedAt: Date(), inputsHash: "sample")
    }
}
