// WeekPlan.swift — the user-facing 7-day plan.
//
// Generated by Planner.generate(memory:routines:today:) and persisted by
// PlanStore. The shape mirrors the spec in PLAN-coach-prereqs.md:
//
//   WeekPlan { days[7], generatedAt, inputsHash }
//   DayPlan  { id, date, kind, title, routineId?, sport?, protected, notes?,
//              generatedReason? }
//
// Phase 11 introduces PlanEdit operations that mutate WeekPlan via PlanStore;
// for now this is read-only (other than full regeneration on weekly check-in
// or onboarding).
//
// Dates are encoded as secondsSince1970 to match SessionStore + MemoryStore.

import Foundation

// MARK: - DayKind

enum DayKind: String, Codable, CaseIterable {
    case lift, sport, mobility, rest, event

    /// Short label rendered in the Week tab badge.
    var label: String {
        switch self {
        case .lift:     return "LIFT"
        case .sport:    return "SPORT"
        case .mobility: return "MOBILITY"
        case .rest:     return "REST"
        case .event:    return "EVENT"
        }
    }

    /// Loose grouping used by Today's hero card to pick a copy treatment.
    var isWorkout: Bool {
        switch self {
        case .lift, .mobility: return true
        case .sport, .rest, .event: return false
        }
    }
}

// MARK: - DayPlan

struct DayPlan: Codable, Identifiable, Hashable {
    var id: UUID = UUID()
    /// Start-of-day (Calendar.startOfDay) — the planner normalizes before stamping.
    var date: Date
    var kind: DayKind
    var title: String
    /// coach.db routine id when kind == .lift / .mobility AND the slot was
    /// satisfied by an explicit user-picked routine (day override). nil for
    /// generated workouts — those carry exercises directly in
    /// `generatedWorkout`.
    var routineId: Int?
    /// Workout assembled exercise-by-exercise from the user's demographic
    /// profile + movement-pattern recipes. Replaces routineId as the primary
    /// source for lift / mobility days. nil for non-workout days or for days
    /// whose slot was overridden by a routineId pick.
    var generatedWorkout: GeneratedWorkout?
    /// Sport for kind == .sport days; nil otherwise.
    var sport: Sport?
    /// User-locked day (Phase 11 protectDay edit) — planner will not auto-move.
    var protected: Bool = false
    var notes: String?
    /// Override session length in minutes; nil = use TrainingMemory.sessionMinutes.
    /// Set by the Phase 11 PlanEdit.shorten op.
    var durationMinutes: Int?
    /// Human-readable rule trace ("4-day plan, day 2 → strength").
    var generatedReason: String?
}

// MARK: - GeneratedWorkout
//
// A workout that the app composed itself from individual coach.db exercises,
// shaped by the user's DemographicProfile + a movement-pattern recipe.
// Bundled routines are still browsable in the library as inspiration / custom
// overrides — they're just no longer the primary content of a planned day.

struct GeneratedWorkout: Codable, Hashable {
    /// Display title — "Push day", "Full body A", "Mobility flow".
    var title: String
    /// One-line summary for the card view: "5 movements · ~45 min".
    var summary: String
    var exercises: [GeneratedExercise]
    var estimatedMinutes: Int
    /// Sentence used in the Today / Week explanation chips — explains *why*
    /// this workout looks the way it does ("Intermediate · push/pull/legs
    /// rotation, day 1 of 3").
    var provenance: String
}

struct GeneratedExercise: Codable, Hashable, Identifiable {
    /// Stable id derived from (planInputsHash, slotIndex, exerciseId) — must
    /// NOT use UUID() so the same memory + slot yields the same id across
    /// regenerations (the inputs-hash drift check relies on stable plans).
    var id: String
    /// coach.db exercises.id — used to fetch full detail / find substitutes.
    var exerciseId: Int
    var name: String
    /// movement_patterns.slug the slot was filled from — for the "why this
    /// exercise" hint and grouping in the UI.
    var pattern: String?
    var isCompound: Bool
    var sets: Int
    /// Free-form reps string ("5", "8-10", "AMRAP", "30s hold"). Bridged
    /// to Int via leading-digit parsing for ActiveSession's targetReps.
    var reps: String
    var restSeconds: Int
    var notes: String?
}

extension GeneratedWorkout {
    /// Composition-based templateId so two generated workouts with the
    /// same exercises share a template id and the SessionStore's
    /// getPreviousSession lookup pulls forward last week's weights even
    /// when the day was regenerated (different DayPlan UUID, same exercise
    /// composition).
    var stableTemplateId: String {
        let signature = exercises.map { String($0.exerciseId) }.joined(separator: ",")
        var hash: UInt64 = 5381
        for byte in signature.utf8 { hash = (hash &* 33) &+ UInt64(byte) }
        return "gen-\(String(hash, radix: 36))"
    }

    /// Bridge to the existing WorkoutTemplate -> ActiveSession runtime so the
    /// log screen + history don't need to learn a new model.
    func toWorkoutTemplate(id: String) -> WorkoutTemplate {
        WorkoutTemplate(
            id: id,
            name: title,
            category: "Generated",
            exercises: exercises.map { gex in
                ExerciseTemplate(
                    id: "gex-\(gex.id)",
                    name: gex.name,
                    type: nil,
                    unit: "lbs",
                    targetSets: gex.sets,
                    targetReps: Self.parseRepsLeading(gex.reps) ?? 8,
                    rest: gex.restSeconds
                )
            }
        )
    }

    /// Render as a list of bundled-style RoutineExercises so the same
    /// RoutineDetailScreen UI can edit a generated workout before starting.
    func toRoutineExercises() -> [RoutineExercise] {
        exercises.enumerated().map { idx, gex in
            RoutineExercise(
                id: -(idx + 1),
                exerciseId: gex.exerciseId,
                name: gex.name,
                position: idx + 1,
                sets: gex.sets,
                reps: gex.reps,
                rest: "\(gex.restSeconds)s",
                notes: gex.notes
            )
        }
    }

    private static func parseRepsLeading(_ s: String) -> Int? {
        let digits = s.prefix(while: { $0.isNumber })
        return Int(digits)
    }
}

// MARK: - WeekPlan

struct WeekPlan: Codable, Hashable {
    /// Exactly 7 days, contiguous from `days.first.date`.
    var days: [DayPlan]
    var generatedAt: Date
    /// Stable hash of the TrainingMemory inputs that produced this plan.
    /// PlanStore compares against the live memory hash to know when to regenerate.
    var inputsHash: String
}

// MARK: - Convenience

extension WeekPlan {
    /// Today's plan, or nil if today's date isn't in the window. Compares by
    /// startOfDay so it's robust across timezones / clock skew within the day.
    func today(now: Date = Date(), calendar: Calendar = .current) -> DayPlan? {
        let target = calendar.startOfDay(for: now)
        return days.first { calendar.isDate($0.date, inSameDayAs: target) }
    }

    /// Compact human label: "Mon — Sun" or "May 14–20".
    var rangeLabel: String {
        guard let first = days.first?.date, let last = days.last?.date else { return "" }
        let f = DateFormatter()
        f.dateFormat = "MMM d"
        return "\(f.string(from: first))–\(f.string(from: last))"
    }
}

// MARK: - Stable input hash
//
// Used by Planner to fingerprint the (TrainingMemory) inputs that produced
// a plan. Stable across runs (no Hashable.hashValue use — that's randomized
// per-launch in Swift). Folds a short canonical string into UInt64 (djb2)
// then base-36-encodes for compactness.

extension TrainingMemory {
    var planInputsHash: String {
        let seasons = seasonsBySport
            .sorted { $0.key.slug < $1.key.slug }
            .map { "\($0.key.slug):\($0.value.rawValue)" }
            .joined(separator: ",")
        let canonical = [
            "v\(schemaVersion)",
            "ps:\(primarySport?.slug ?? "_")",
            "sp:\(sports.map(\.slug).sorted().joined(separator: ","))",
            "fc:\(focuses.map(\.rawValue).joined(separator: ","))",
            "ds:\(defaultSeason.rawValue)",
            "ss:\(seasons)",
            "mn:\(sessionMinutes)",
            "ld:\(liftDaysPerWeek)",
            "eq:\(equipment.map(\.rawValue).sorted().joined(separator: ","))",
            "ex:\(experience.rawValue)"
        ].joined(separator: "|")
        var hash: UInt64 = 5381
        for byte in canonical.utf8 {
            hash = (hash &* 33) &+ UInt64(byte)
        }
        return String(hash, radix: 36)
    }
}

// MARK: - Sample plan (preview / tests)

extension WeekPlan {
    /// Deterministic sample for previews + tests. Mon=lift, Tue=sport,
    /// Wed=mobility, Thu=lift, Fri=rest, Sat=sport, Sun=rest.
    static func sample(startingAt date: Date = Date()) -> WeekPlan {
        let cal = Calendar.current
        let start = cal.startOfDay(for: date)
        let kinds: [DayKind] = [.lift, .sport, .mobility, .lift, .rest, .sport, .rest]
        let titles = ["Push & Pull", "Climb session", "Hip mobility", "Lower body", "Rest", "Trail run", "Rest"]
        let days: [DayPlan] = (0..<7).map { i in
            DayPlan(
                date: cal.date(byAdding: .day, value: i, to: start) ?? start,
                kind: kinds[i],
                title: titles[i],
                routineId: kinds[i].isWorkout ? 1 : nil,
                sport: kinds[i] == .sport ? Sport.catalog.first(where: { $0.slug == "climbing" }) : nil,
                generatedReason: "sample data"
            )
        }
        return WeekPlan(days: days, generatedAt: Date(), inputsHash: "sample")
    }
}
