-- General weightlifting canon — fills the gap where the 711-exercise DB had
-- sport-flavored variants but not the canonical lifts themselves.
-- IDs 900-984. Mirror file lives at upstream phase-training/data/exercises/.

BEGIN TRANSACTION;

INSERT INTO exercises
  (id, name, slug, description, instructions, cues,
   difficulty, modality, movement_plane, energy_system, contraction_type,
   is_unilateral, is_compound, environment,
   default_sets, default_reps, default_rest, default_tempo,
   recovery_demand, cns_load, intensity_category, fatigue_type, swap_group,
   low_energy_suitable, pre_event_safe, warmup_compatible,
   regression, progression, tags, source_type) VALUES

-- ===== BARBELL PRESSING =====
(900,'Barbell Bench Press','barbell-bench-press',
 'Flat barbell bench press — primary horizontal-push strength lift.',
 'Lie on a flat bench with eyes under the bar. Grip slightly wider than shoulder width. Unrack, brace, lower the bar to mid-chest with control, then press to lockout. Keep feet planted and shoulder blades retracted.',
 '["shoulder blades pinned","tuck elbows ~45°","drive bar in slight arc","feet planted"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'5-8','2-3 min','2-0-1-0',
 7,7,'high','["chest","triceps","shoulders"]','press_bilateral_barbell',
 0,0,0,'Dumbbell bench press.','Pause bench press or weight increase.',
 '["bench","barbell","horizontal push","powerlifting","chest"]','expert_consensus'),

(901,'Incline Barbell Bench Press','incline-barbell-bench-press',
 'Incline (30-45°) barbell bench press — upper-chest and front-delt bias.',
 'Set bench to 30-45°. Grip slightly wider than shoulders, unrack, lower to upper chest, press to lockout. Keep ribs over hips, do not flare the elbows.',
 '["bar lands on upper chest","elbows ~45°","no excessive arch"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'6-10','2 min','2-0-1-0',
 6,6,'high','["chest","shoulders","triceps"]','press_bilateral_barbell',
 0,0,0,'Incline dumbbell press.','Heavier load or pause.',
 '["incline","barbell","upper chest","bench"]','expert_consensus'),

(902,'Close-Grip Bench Press','close-grip-bench-press',
 'Narrow-grip barbell bench press — triceps and lockout bias for press strength carry-over.',
 'Grip shoulder-width or slightly narrower. Tuck elbows close to the body, lower bar to lower chest, press to lockout. Avoid wrist-width grip — keep wrists stacked.',
 '["elbows tucked tight","grip about shoulder-width","drive triceps to lockout"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'5-8','2 min','2-0-1-0',
 6,6,'high','["triceps","chest"]','press_bilateral_barbell',
 0,0,0,'Dumbbell close-grip press.','Pin press or floor press at heavier load.',
 '["close grip","bench","triceps","powerlifting"]','expert_consensus'),

(903,'Floor Press (Barbell)','floor-press-barbell',
 'Barbell bench press from the floor — partial ROM with hard pause for lockout strength.',
 'Lie on the floor under a barbell in a rack or with spotters. Lower the bar until the upper arms touch the floor, pause briefly, then press. Eliminates leg drive.',
 '["pause on the floor","do not bounce triceps","press straight up"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'4-6','2-3 min',NULL,
 6,6,'high','["triceps","chest","shoulders"]','press_bilateral_barbell',
 0,0,0,'Dumbbell floor press.','Heavier load or longer pause.',
 '["floor press","barbell","lockout","powerlifting"]','expert_consensus'),

(904,'Barbell Overhead Press (Strict)','barbell-overhead-press',
 'Standing strict barbell press — vertical-push foundation, no leg drive.',
 'Set bar at front rack, hip-width stance. Brace hard, press the bar straight overhead, pushing head through at lockout. Lower under control. No knee bend.',
 '["squeeze glutes","ribs over pelvis","press head through at top"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'5-8','2-3 min','2-0-1-0',
 7,7,'high','["shoulders","triceps","core"]','press_bilateral_overhead',
 0,0,0,'Seated dumbbell press.','Push press or weight increase.',
 '["overhead press","OHP","strict press","military press","barbell"]','expert_consensus'),

(905,'Push Press','push-press',
 'Overhead barbell press with a leg-drive dip — moves heavier load than strict press.',
 'Front-rack the bar. Small fast dip at the knees (10-15°), then drive vertically through the legs to launch the bar overhead. Finish with arms straight and feet planted.',
 '["short dip","drive straight up not forward","catch with locked elbows"]',
 'advanced','power','sagittal','phosphagen','concentric',
 0,1,'gym',5,'3-5','2-3 min',NULL,
 7,8,'high','["shoulders","triceps","quads","cns"]','press_bilateral_overhead',
 0,0,0,'Strict press.','Push jerk or heavier load.',
 '["push press","overhead","power","crossfit"]','expert_consensus'),

(906,'Push Jerk','push-jerk',
 'Push press with a re-bend under the bar — receives load with bent knees, drives up to lockout.',
 'Dip and drive as in a push press. As the bar leaves the shoulders, drop fast into a partial squat with arms locked overhead, then stand to finish.',
 '["punch under the bar","catch with locked arms","stand to finish"]',
 'advanced','power','sagittal','phosphagen','concentric',
 0,1,'gym',5,'2-3','2-3 min',NULL,
 7,8,'high','["shoulders","quads","cns"]','press_bilateral_overhead',
 0,0,0,'Push press.','Split jerk or heavier load.',
 '["push jerk","overhead","oly","crossfit"]','expert_consensus'),

-- ===== DUMBBELL PRESSING =====
(907,'Incline Dumbbell Bench Press','incline-dumbbell-bench-press',
 'Incline dumbbell press — upper chest with independent arm path.',
 'Set bench to 30-45°. Press dumbbells from shoulder level to lockout, palms facing forward or slightly inward. Lower with control.',
 '["wrists stacked over elbows","do not clang dumbbells at top","control eccentric"]',
 'beginner','strength','sagittal','phosphagen','concentric',
 0,1,'home',4,'8-12','90 sec','2-0-1-0',
 5,5,'moderate','["chest","shoulders","triceps"]','press_bilateral_dumbbell',
 0,0,0,'Lighter dumbbells.','Heavier dumbbells or barbell incline.',
 '["incline","dumbbell","upper chest"]','expert_consensus'),

(908,'Seated Dumbbell Press','seated-dumbbell-press',
 'Seated dumbbell overhead press — vertical push with independent arms.',
 'Sit on a bench with back support (or upright). Press dumbbells from shoulder level overhead. Lower under control, dumbbells stop near the ears.',
 '["wrists stacked","ribs down","do not arch lumbar"]',
 'beginner','strength','sagittal','phosphagen','concentric',
 0,1,'home',4,'8-12','90 sec',NULL,
 5,5,'moderate','["shoulders","triceps"]','press_bilateral_overhead',
 0,0,0,'Lighter weight or single-arm.','Standing dumbbell press or heavier load.',
 '["seated press","dumbbell","overhead","shoulders"]','expert_consensus'),

(909,'Arnold Press','arnold-press',
 'Rotational dumbbell overhead press — sweeps through full shoulder ROM.',
 'Sit holding dumbbells in front of shoulders, palms facing you. Press up while rotating palms to face forward at lockout. Reverse on the descent.',
 '["smooth rotation","do not bang dumbbells","keep core braced"]',
 'intermediate','strength','transverse','phosphagen','concentric',
 0,1,'gym',3,'10-12','90 sec',NULL,
 5,5,'moderate','["shoulders","triceps"]','press_bilateral_overhead',
 0,0,0,'Standard seated DB press.','Heavier or single-arm Arnold.',
 '["arnold press","dumbbell","shoulders","rotation"]','expert_consensus'),

-- ===== OLYMPIC LIFTS =====
(910,'Hang Clean','hang-clean',
 'Power clean from the hang — bar starts at mid-thigh, no floor pull.',
 'Stand with bar at mid-thigh. Hinge slightly, then explode by extending hips, knees, ankles. Shrug, pull under, and catch the bar on the shoulders in a partial squat.',
 '["bar stays close","fast hip extension","fast elbows under bar"]',
 'advanced','power','sagittal','phosphagen','concentric',
 0,1,'gym',5,'3-5','2-3 min',NULL,
 7,8,'high','["posterior_chain","quads","traps","cns"]','clean_bilateral_barbell',
 0,0,0,'Hang muscle clean or hang high pull.','Power clean from floor.',
 '["clean","oly","power","crossfit"]','expert_consensus'),

(911,'Clean Pull','clean-pull',
 'Clean lift through the second pull, no catch — top-end pulling strength.',
 'Set up as for a clean. Pull from the floor, extend explosively at the hips and shrug hard, but do not pull under the bar. Land flat-footed with shoulders shrugged.',
 '["finish the pull","shrug at the top","no early arm bend"]',
 'advanced','strength','sagittal','phosphagen','concentric',
 0,1,'gym',5,'3-5','2-3 min',NULL,
 7,7,'high','["posterior_chain","traps","cns"]','pull_bilateral_barbell',
 0,0,0,'RDL.','Power clean or heavier clean pull.',
 '["clean pull","oly","pull"]','expert_consensus'),

(912,'Power Snatch','power-snatch',
 'Snatch caught above parallel — wide-grip overhead lift from the floor.',
 'Set up over the bar with wide snatch grip. Pull off the floor smoothly, explode at the hips, then pull under and catch the bar locked out overhead in a partial squat. Stand.',
 '["bar in straight line","punch overhead","catch above parallel"]',
 'advanced','power','sagittal','phosphagen','concentric',
 0,1,'gym',5,'2-3','2-3 min',NULL,
 8,9,'high','["full_body","cns","shoulders"]','snatch_bilateral_barbell',
 0,0,0,'Snatch high pull or hang snatch.','Full snatch.',
 '["snatch","oly","power","crossfit"]','expert_consensus'),

(913,'Snatch Pull','snatch-pull',
 'Snatch lift through the second pull, no catch — overhead-pull strength builder.',
 'Set up with snatch-width grip. Pull from the floor, extend explosively at the hips and shrug hard, no catch. Land flat-footed.',
 '["finish tall","high shrug","do not curl arms"]',
 'advanced','strength','sagittal','phosphagen','concentric',
 0,1,'gym',5,'3-5','2-3 min',NULL,
 7,7,'high','["posterior_chain","traps","cns"]','pull_bilateral_barbell',
 0,0,0,'Snatch-grip RDL.','Power snatch.',
 '["snatch pull","oly"]','expert_consensus'),

(914,'Clean & Jerk','clean-and-jerk',
 'Full clean from the floor followed by a jerk overhead — total-body Olympic lift.',
 'Clean the bar from the floor to the front rack. Recover. Dip and drive the bar overhead in a push jerk or split jerk. Stand to finish with bar locked out.',
 '["clean then reset","aggressive jerk drive","stable lockout"]',
 'elite','power','sagittal','phosphagen','concentric',
 0,1,'gym',5,'1-3','3-4 min',NULL,
 9,10,'max','["full_body","cns"]','clean_bilateral_barbell',
 0,0,0,'Hang clean + push press.','Heavier load.',
 '["clean and jerk","oly","crossfit"]','expert_consensus'),

(915,'Snatch','snatch',
 'Full snatch — bar from floor to overhead in one move, catch in deep squat.',
 'Set up over the bar with wide snatch grip. Pull, extend, and pull under aggressively, catching the bar overhead in a full overhead squat. Stand to finish.',
 '["bar close to body","punch up under bar","upright torso in catch"]',
 'elite','power','sagittal','phosphagen','concentric',
 0,1,'gym',5,'1-3','3-4 min',NULL,
 9,10,'max','["full_body","cns","shoulders"]','snatch_bilateral_barbell',
 0,0,0,'Power snatch.','Heavier load.',
 '["snatch","oly","full snatch"]','expert_consensus'),

-- ===== DEADLIFT & SQUAT VARIANTS =====
(916,'Sumo Deadlift','sumo-deadlift',
 'Wide-stance deadlift — shorter pull range, hip- and adductor-driven.',
 'Stance wide, toes turned out 30-45°, grip the bar inside the legs. Drop hips, chest up, pull the bar straight up by pushing the floor away. Stand and lock out.',
 '["knees track over toes","chest up","squeeze glutes at top"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'3-5','2-3 min',NULL,
 8,8,'high','["posterior_chain","adductors","grip"]','hinge_bilateral_barbell',
 0,0,0,'Trap bar deadlift.','Heavier load.',
 '["sumo","deadlift","powerlifting","hinge"]','expert_consensus'),

(917,'Stiff-Leg Deadlift','stiff-leg-deadlift',
 'Deadlift with minimal knee bend and lower-back rounding — heavy hamstring/erector emphasis.',
 'Stand with feet hip-width, bar in front. Keep knees nearly straight. Hinge at hips, lower bar past shins, then drive hips forward to stand. Maintain neutral spine.',
 '["minimal knee bend","hinge at hips","feel hamstring stretch"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'6-10','2 min','3-0-1-0',
 6,5,'high','["hamstrings","erectors","glutes"]','hinge_bilateral_barbell',
 0,0,0,'Romanian deadlift.','Deficit stiff-leg.',
 '["stiff leg","deadlift","SLDL","hamstrings"]','expert_consensus'),

(918,'Deficit Deadlift','deficit-deadlift',
 'Conventional deadlift performed from a 1-3" platform — extra range, off-the-floor strength.',
 'Stand on a low platform with the bar at normal height. Set up as for conventional deadlift but with knees more bent. Pull from the deeper position.',
 '["chest up off the floor","push the floor away","do not round low back"]',
 'advanced','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'3-5','2-3 min',NULL,
 8,8,'high','["posterior_chain","quads","grip"]','hinge_bilateral_barbell',
 0,0,0,'Conventional deadlift.','Larger deficit or heavier load.',
 '["deficit","deadlift","powerlifting"]','expert_consensus'),

(919,'Pause Squat','pause-squat',
 'Back squat with a 2-3 second pause in the hole — kills the stretch reflex, builds bottom-end strength.',
 'Set up as for back squat. Descend to depth, pause 2-3 seconds without losing tightness, then drive up.',
 '["stay tight in the hole","do not collapse","drive straight up"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'3-5','2-3 min','3-3-1-0',
 7,7,'high','["quads","glutes","cns"]','squat_bilateral_barbell',
 0,0,0,'Goblet squat with pause.','Heavier load or longer pause.',
 '["pause squat","powerlifting","strength"]','expert_consensus'),

(920,'Box Squat','box-squat',
 'Back squat to a box at parallel or below — teaches depth, breaks eccentric/concentric.',
 'Set a box at the desired depth behind you. Descend under control, sit fully on the box without losing tightness, then drive up.',
 '["sit back not down","stay tight on box","do not bounce"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'3-5','2-3 min',NULL,
 7,7,'high','["quads","glutes","posterior_chain"]','squat_bilateral_barbell',
 0,0,0,'Bodyweight box squat.','Heavier load or wider stance.',
 '["box squat","powerlifting"]','expert_consensus'),

(921,'Barbell Good Morning','barbell-good-morning',
 'Hip hinge with bar on the back — heavy hamstring and erector emphasis.',
 'Bar on upper back as in a high-bar squat. Slight knee bend. Hinge at hips, lowering torso until parallel or until hamstrings limit. Stand by driving hips forward.',
 '["hinge at hips","neutral spine","slight knee bend"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',3,'6-10','2 min','3-0-1-0',
 6,5,'moderate','["hamstrings","erectors","glutes"]','hinge_bilateral_barbell',
 0,0,0,'Dumbbell good morning.','Heavier load.',
 '["good morning","hinge","barbell","powerlifting"]','expert_consensus'),

-- ===== VERTICAL PULLS =====
(922,'Pull-Up','pull-up',
 'Bodyweight pull-up, overhand grip — vertical pulling foundation.',
 'Hang from bar with overhand grip slightly wider than shoulders. Pull until chin clears the bar. Lower with control to a dead hang.',
 '["pull elbows to ribs","squeeze lats","control the descent"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'home',4,'5-10','2 min',NULL,
 6,6,'high','["lats","biceps","grip"]','pull_bilateral_vertical',
 0,0,0,'Band-assisted pull-up or inverted row.','Weighted pull-up.',
 '["pull up","vertical pull","bodyweight","calisthenics"]','expert_consensus'),

(923,'Chin-Up','chin-up',
 'Bodyweight chin-up, supinated grip — biceps-biased vertical pull.',
 'Hang from bar with underhand (palms-facing-you) grip shoulder-width. Pull until chin clears the bar. Lower with control.',
 '["squeeze biceps","drive elbows down","full hang at bottom"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'home',4,'5-10','2 min',NULL,
 6,6,'high','["lats","biceps","grip"]','pull_bilateral_vertical',
 0,0,0,'Band-assisted chin-up.','Weighted chin-up.',
 '["chin up","vertical pull","bodyweight","biceps"]','expert_consensus'),

(924,'Neutral-Grip Pull-Up','neutral-grip-pull-up',
 'Pull-up with palms facing each other — shoulder-friendly vertical pull.',
 'Use a parallel-grip handle or rings. Hang neutral, pull until chin clears the bar, lower under control.',
 '["palms face each other","elbows track straight","full hang"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'home',4,'5-10','2 min',NULL,
 6,6,'high','["lats","biceps","brachialis"]','pull_bilateral_vertical',
 0,0,0,'Band-assisted neutral pull-up.','Weighted neutral pull-up.',
 '["neutral grip","pull up","shoulder friendly"]','expert_consensus'),

(925,'Lat Pulldown (Wide-Grip)','lat-pulldown-wide',
 'Wide-grip lat pulldown — vertical pull for those still working up to bodyweight pull-ups, or for high-volume back work.',
 'Sit at the lat pulldown machine, thighs anchored. Grip bar wide overhand. Pull bar to upper chest, leading with the elbows. Control the return.',
 '["chest up","pull to upper chest","squeeze lats"]',
 'beginner','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'8-12','90 sec',NULL,
 5,4,'moderate','["lats","biceps","mid_back"]','pull_bilateral_vertical',
 0,0,0,'Band-assisted pulldown.','Heavier load or pull-up.',
 '["lat pulldown","vertical pull","back"]','expert_consensus'),

-- ===== ROWS =====
(926,'T-Bar Row','t-bar-row',
 'Landmine or T-bar handle row — bilateral horizontal pull with mixed-grip handle.',
 'Straddle the bar with V-handle attached at the loaded end. Hinge to ~45°, brace, row the handle to the lower chest.',
 '["chest up","pull to lower chest","squeeze mid back"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'8-12','90 sec',NULL,
 6,5,'moderate','["lats","mid_back","rhomboids","biceps"]','row_bilateral',
 0,0,0,'Chest-supported DB row.','Heavier load.',
 '["t-bar row","row","back"]','expert_consensus'),

(927,'Pendlay Row','pendlay-row',
 'Strict barbell row from the floor each rep — explosive concentric, dead-stop reset.',
 'Hinge to torso parallel to floor. Bar starts on the floor each rep. Row explosively to the lower sternum, then return the bar fully to the floor.',
 '["torso stays parallel","dead stop between reps","explosive pull"]',
 'advanced','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'4-6','2 min',NULL,
 7,7,'high','["lats","mid_back","erectors"]','row_bilateral',
 0,0,0,'Barbell bent-over row.','Heavier load.',
 '["pendlay row","barbell","row","powerlifting"]','expert_consensus'),

(928,'Meadows Row','meadows-row',
 'Single-arm landmine row using an overhand grip and staggered stance — heavy unilateral back work.',
 'Stand to the side of a landmine bar in a staggered stance. Hinge over, grip the end of the bar overhand, row the bar to the hip. Switch sides.',
 '["square hips down","pull elbow back","squeeze at the top"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 1,1,'gym',3,'8-10/side','90 sec',NULL,
 5,5,'moderate','["lats","mid_back","biceps"]','row_unilateral',
 0,0,0,'Single-arm DB row.','Heavier load.',
 '["meadows row","landmine","row","unilateral"]','expert_consensus'),

(929,'Seal Row','seal-row',
 'Prone barbell or dumbbell row with chest supported on a raised bench — strict back work, no torso swing.',
 'Lie face-down on an elevated bench with bar/dumbbells hanging below. Row to the bench, squeeze, control the return. No leg or torso English.',
 '["chest stays pinned","row with the back not the body","pause at top"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'8-12','90 sec',NULL,
 5,4,'moderate','["lats","mid_back","rhomboids"]','row_bilateral',
 0,0,0,'Chest-supported DB row.','Heavier load.',
 '["seal row","strict row","back"]','expert_consensus'),

(930,'Machine Chest-Supported Row','machine-row',
 'Plate-loaded or selectorized chest-supported row — fixed path, strict back work.',
 'Sit at the row machine with chest pad supporting torso. Pull handles to the ribs, squeeze, control the return.',
 '["chest stays on the pad","pull elbows back","squeeze the mid back"]',
 'beginner','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'10-15','90 sec',NULL,
 4,3,'moderate','["lats","mid_back","rhomboids","biceps"]','row_bilateral',
 0,0,0,'Seated cable row.','Heavier load.',
 '["machine row","chest supported","back"]','expert_consensus'),

-- ===== LEG MACHINES & SQUAT MACHINES =====
(931,'Leg Press','leg-press',
 'Plate-loaded or selectorized leg press — heavy quad/glute work with supported torso.',
 'Sit in the leg press machine, feet shoulder-width on the platform. Lower the platform until knees track around 90°. Press through full foot to lockout (do not snap knees).',
 '["full foot contact","do not lock knees hard","control eccentric"]',
 'beginner','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'8-15','2 min','2-0-1-0',
 5,4,'moderate','["quads","glutes","adductors"]','squat_bilateral_machine',
 0,0,0,'Goblet squat.','Heavier load.',
 '["leg press","quads","machine"]','expert_consensus'),

(932,'Hack Squat (Machine)','hack-squat-machine',
 'Sled-style hack squat — supported squat pattern with heavy quad emphasis.',
 'Position shoulders under pads, feet shoulder-width on platform. Descend until thighs are parallel, drive up through full foot to lockout.',
 '["heels down","knees track over toes","control descent"]',
 'beginner','strength','sagittal','phosphagen','concentric',
 0,1,'gym',4,'8-12','2 min',NULL,
 6,5,'high','["quads","glutes"]','squat_bilateral_machine',
 0,0,0,'Goblet squat.','Heavier load.',
 '["hack squat","machine","quads"]','expert_consensus'),

(933,'Leg Extension','leg-extension',
 'Seated machine knee extension — isolated quad work, especially the rectus femoris and VMO.',
 'Sit in the machine, ankles behind the pad. Extend knees fully against resistance, squeeze at the top, lower with control.',
 '["squeeze at full extension","control eccentric","keep hips planted"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec','2-1-2-0',
 3,2,'moderate','["quads"]','isolation_knee_extension',
 1,1,0,'Lighter load or partial range.','Heavier load or pause at top.',
 '["leg extension","quads","isolation"]','expert_consensus'),

(934,'Lying Leg Curl','lying-leg-curl',
 'Prone machine hamstring curl — isolated knee-flexion hamstring work.',
 'Lie face-down on the machine, ankles under the pad. Curl heels toward glutes, squeeze, lower with control.',
 '["squeeze hamstrings at top","do not arch lumbar","slow eccentric"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec','2-1-2-0',
 4,3,'moderate','["hamstrings"]','isolation_knee_flexion',
 1,1,0,'Slider hamstring curl.','Heavier load.',
 '["leg curl","hamstrings","isolation"]','expert_consensus'),

(935,'Seated Leg Curl','seated-leg-curl',
 'Seated machine hamstring curl — hip-flexed knee flexion, distal hamstring bias.',
 'Sit in machine with thigh pad locking legs in place. Curl heels under, squeeze, return with control.',
 '["squeeze hamstrings","slow eccentric","do not slam stack"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 4,3,'moderate','["hamstrings"]','isolation_knee_flexion',
 1,1,0,'Lying leg curl.','Heavier load.',
 '["seated leg curl","hamstrings","isolation"]','expert_consensus'),

(936,'Hip Abduction (Machine)','hip-abduction-machine',
 'Seated machine hip abduction — glute medius and minimus work.',
 'Sit in the machine, pads outside thighs. Press knees apart against resistance, squeeze glutes, return with control.',
 '["squeeze glutes at end range","do not lean forward","slow tempo"]',
 'beginner','strength','frontal','glycolytic','concentric',
 0,0,'gym',3,'12-15','60 sec',NULL,
 3,2,'low','["glute_medius"]','isolation_hip_abduction',
 1,1,0,'Mini-band side-step.','Heavier load.',
 '["hip abduction","glute medius","machine"]','expert_consensus'),

(937,'Hip Adduction (Machine)','hip-adduction-machine',
 'Seated machine hip adduction — adductor strengthening.',
 'Sit in the machine, pads inside thighs. Squeeze knees together against resistance, return with control.',
 '["squeeze inner thighs","slow tempo","do not slam stack"]',
 'beginner','strength','frontal','glycolytic','concentric',
 0,0,'gym',3,'12-15','60 sec',NULL,
 3,2,'low','["adductors"]','isolation_hip_adduction',
 1,1,0,'Copenhagen adductor lift.','Heavier load.',
 '["hip adduction","adductors","machine"]','expert_consensus'),

(938,'Cable Pull-Through','cable-pull-through',
 'Hip-hinge with cable between the legs — glute and hamstring isolation with low spinal load.',
 'Face away from cable column with rope between legs. Hinge at the hips, hands tracking down between the knees. Stand by driving the hips forward, squeezing glutes at lockout.',
 '["hinge not squat","squeeze glutes at top","neutral spine"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,1,'gym',3,'10-15','75 sec',NULL,
 4,3,'moderate','["glutes","hamstrings"]','hinge_bilateral_cable',
 1,1,0,'Banded pull-through.','Heavier cable load or barbell RDL.',
 '["pull through","cable","glutes","hinge"]','expert_consensus'),

(939,'45° Back Extension','back-extension-45',
 '45-degree hyperextension — glute, hamstring, erector strength with low spinal compression.',
 'Set up in a 45° hyper bench with hips on the pad. Hinge at the hips, lowering torso, then extend back to neutral by squeezing glutes. Do not hyperextend lumbar.',
 '["squeeze glutes at top","do not lock out into hyperextension","neutral spine"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,1,'gym',3,'10-15','60 sec',NULL,
 4,3,'moderate','["erectors","glutes","hamstrings"]','hinge_bilateral_hyper',
 1,1,0,'Bodyweight only.','Add weight plate held to chest.',
 '["back extension","hyperextension","glutes","erectors"]','expert_consensus'),

(940,'Reverse Hyperextension','reverse-hyper',
 'Reverse hyperextension machine — glute, hamstring, erector work with traction-style spinal decompression.',
 'Lie face-down on the reverse hyper, hips at the edge. Swing legs from hang to horizontal by squeezing glutes. Control the descent.',
 '["squeeze glutes","do not arch hard","control swing"]',
 'intermediate','strength','sagittal','glycolytic','concentric',
 0,1,'gym',3,'10-15','60 sec',NULL,
 4,3,'moderate','["glutes","hamstrings","erectors"]','hinge_bilateral_hyper',
 1,1,0,'Lighter load.','Heavier load.',
 '["reverse hyper","glutes","decompression"]','expert_consensus'),

(941,'Glute-Ham Raise (GHR)','glute-ham-raise',
 'GHD glute-ham raise — knee-flexion hamstring lift with hip-extension assist.',
 'Set up on a glute-ham developer, knees just behind pad. Start with torso vertical, lower under control until horizontal, then curl back up by contracting hamstrings.',
 '["squeeze hamstrings","do not collapse at the bottom","control eccentric"]',
 'advanced','strength','sagittal','phosphagen','eccentric',
 0,1,'gym',3,'5-8','2 min','3-0-1-0',
 6,5,'high','["hamstrings","glutes","erectors"]','isolation_knee_flexion',
 0,1,0,'Banded-assisted GHR or Nordic curl.','Weighted GHR.',
 '["GHR","glute ham raise","hamstrings"]','expert_consensus'),

(942,'Seated Calf Raise','seated-calf-raise',
 'Seated machine calf raise — soleus-biased isolation.',
 'Sit in the machine, knees under pads, balls of feet on the platform. Press up onto the toes, squeeze, lower under stretch.',
 '["full ROM","squeeze at top","slow eccentric"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'12-20','45 sec',NULL,
 3,2,'low','["soleus","calves"]','isolation_calf',
 1,1,0,'Bodyweight seated.','Heavier load.',
 '["seated calf raise","soleus","isolation"]','expert_consensus'),

(943,'Walking Lunge','walking-lunge',
 'Loaded walking lunge — alternating-leg quad/glute work that progresses distance.',
 'Hold dumbbells at the sides (or bar on back). Step forward into a lunge, knee tracking over toes, then push off the back leg and step forward into the next lunge.',
 '["torso upright","knee over toe","do not collapse"]',
 'intermediate','strength','sagittal','glycolytic','concentric',
 1,1,'gym',3,'10-12/side','2 min',NULL,
 6,5,'high','["quads","glutes","adductors"]','lunge_alternating',
 0,0,0,'Bodyweight walking lunge.','Heavier load or longer distance.',
 '["walking lunge","unilateral","quads"]','expert_consensus'),

(944,'Reverse Lunge (Barbell)','reverse-lunge-barbell',
 'Barbell reverse lunge — knee-friendly unilateral squat pattern.',
 'Bar on back. Step one foot back into a lunge, dropping the back knee toward the floor. Drive through the front foot to return.',
 '["torso upright","step back not down","drive through front heel"]',
 'intermediate','strength','sagittal','glycolytic','concentric',
 1,1,'gym',3,'6-10/side','2 min',NULL,
 6,5,'high','["quads","glutes"]','lunge_unilateral',
 0,0,0,'Bodyweight reverse lunge.','Heavier load.',
 '["reverse lunge","barbell","unilateral"]','expert_consensus'),

(945,'Forward Lunge (Dumbbell)','forward-lunge-dumbbell',
 'Dumbbell forward lunge — classic alternating-leg loaded lunge.',
 'Hold dumbbells at the sides. Step forward into a lunge, drop the back knee under control, then push back to the start.',
 '["knee over toes","torso tall","push through front heel"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 1,1,'home',3,'8-10/side','90 sec',NULL,
 5,4,'moderate','["quads","glutes"]','lunge_alternating',
 0,0,0,'Bodyweight forward lunge.','Heavier dumbbells.',
 '["forward lunge","dumbbell","unilateral"]','expert_consensus'),

-- ===== BICEPS =====
(946,'Barbell Curl','barbell-curl',
 'Standing barbell curl — primary bilateral biceps lift.',
 'Stand with feet hip-width, bar at thighs in supinated grip. Curl the bar to the shoulders by flexing the elbows. Lower with control.',
 '["elbows by your sides","no torso swing","squeeze at top"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'8-12','60 sec','2-0-1-0',
 4,3,'moderate','["biceps","brachialis"]','isolation_elbow_flexion',
 1,1,0,'Dumbbell curl.','Heavier load or strict tempo.',
 '["barbell curl","biceps","isolation"]','expert_consensus'),

(947,'EZ-Bar Curl','ez-bar-curl',
 'Curl with EZ (cambered) bar — wrist-friendly biceps lift.',
 'Stand with EZ bar at thighs, grip the angled portion. Curl to shoulders, lower with control.',
 '["wrists in neutral","elbows fixed","slow eccentric"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'8-12','60 sec',NULL,
 4,3,'moderate','["biceps","brachialis"]','isolation_elbow_flexion',
 1,1,0,'Dumbbell curl.','Heavier load.',
 '["ez bar","curl","biceps"]','expert_consensus'),

(948,'Dumbbell Curl','dumbbell-curl',
 'Standing dumbbell biceps curl — alternating or simultaneous.',
 'Stand with dumbbells at sides, palms facing in. Curl one or both dumbbells, supinating the wrist as they pass the thigh. Lower with control.',
 '["squeeze at top","supinate as you curl","no torso swing"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'10-12/side','60 sec',NULL,
 3,2,'moderate','["biceps","brachialis"]','isolation_elbow_flexion',
 1,1,0,'Lighter dumbbells.','Heavier dumbbells or incline curl.',
 '["dumbbell curl","biceps","isolation"]','expert_consensus'),

(949,'Incline Dumbbell Curl','incline-dumbbell-curl',
 'Curl on incline bench — bias toward long-head of biceps via shoulder extension.',
 'Sit on incline bench (45-60°), dumbbells hanging at sides. Curl without lifting the elbows forward. Lower fully each rep.',
 '["full stretch at bottom","elbows do not drift","squeeze at top"]',
 'intermediate','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'8-12','75 sec','3-0-1-0',
 4,3,'moderate','["biceps","brachialis"]','isolation_elbow_flexion',
 1,1,0,'Standing DB curl.','Heavier load or slower eccentric.',
 '["incline curl","biceps","stretch"]','expert_consensus'),

(950,'Hammer Curl','hammer-curl',
 'Neutral-grip curl — brachialis and brachioradialis bias.',
 'Hold dumbbells with palms facing each other. Curl without rotating the wrist. Lower with control.',
 '["neutral grip","squeeze at top","no torso swing"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'10-12/side','60 sec',NULL,
 3,2,'moderate','["brachialis","brachioradialis","biceps"]','isolation_elbow_flexion',
 1,1,0,'Lighter dumbbells.','Heavier load or cross-body hammer.',
 '["hammer curl","brachialis","biceps"]','expert_consensus'),

(951,'Concentration Curl','concentration-curl',
 'Seated single-arm dumbbell curl with elbow braced on inner thigh — strict biceps isolation.',
 'Sit on a bench, elbow braced on inner thigh, dumbbell hanging. Curl to shoulder, squeeze hard at the top, lower fully.',
 '["squeeze the peak","no shoulder swing","full extension at bottom"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 1,0,'home',3,'10-12/side','60 sec',NULL,
 3,2,'low','["biceps"]','isolation_elbow_flexion',
 1,1,0,'Lighter dumbbell.','Heavier load.',
 '["concentration curl","biceps","isolation"]','expert_consensus'),

(952,'Cable Curl','cable-curl',
 'Standing cable curl with bar or rope — constant tension biceps work.',
 'Face a low cable with a bar or rope attached. Curl by flexing the elbows, keeping them at your sides. Lower under tension.',
 '["constant tension","elbows fixed","squeeze at top"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 3,2,'moderate','["biceps","brachialis"]','isolation_elbow_flexion',
 1,1,0,'Banded curl.','Heavier cable load.',
 '["cable curl","biceps","constant tension"]','expert_consensus'),

-- ===== TRICEPS =====
(953,'Tricep Pushdown','tricep-pushdown',
 'Cable triceps pushdown with V-bar or straight bar — primary cable triceps lift.',
 'Stand at a high cable with a V-bar or straight bar attached. Tuck elbows at sides, push the bar down to lockout, squeeze triceps. Return with control.',
 '["elbows at sides","fully extend at bottom","no torso swing"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 3,2,'moderate','["triceps"]','isolation_elbow_extension',
 1,1,0,'Banded pushdown.','Heavier cable load.',
 '["pushdown","triceps","cable"]','expert_consensus'),

(954,'Rope Pushdown','rope-pushdown',
 'Cable rope triceps pushdown with end-range split — lateral-head triceps emphasis.',
 'Use a rope attachment on a high cable. Push down, splitting the rope outward at the bottom. Squeeze triceps, return with control.',
 '["split the rope at the bottom","elbows pinned","squeeze hard"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 3,2,'moderate','["triceps"]','isolation_elbow_extension',
 1,1,0,'Banded rope pushdown.','Heavier cable load.',
 '["rope pushdown","triceps","cable"]','expert_consensus'),

(955,'Overhead Cable Triceps Extension','overhead-cable-tricep-extension',
 'Cable overhead triceps extension with rope — long-head triceps emphasis in lengthened position.',
 'Face away from a cable column with rope attached at low or mid pulley. Rope behind head, elbows pointing forward. Extend arms overhead, return with control.',
 '["elbows by ears","full stretch at bottom","control return"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 3,2,'moderate','["triceps"]','isolation_elbow_extension',
 1,1,0,'Banded overhead extension.','Heavier cable load.',
 '["overhead tricep extension","triceps","long head"]','expert_consensus'),

(956,'Tricep Kickback (Dumbbell)','tricep-kickback',
 'Bent-over single-arm dumbbell kickback — strict triceps isolation.',
 'Hinge over with one hand on a bench. Pin upper arm parallel to torso. Extend the elbow until arm is straight, squeeze, return with control.',
 '["pin the upper arm","squeeze at extension","do not swing"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 1,0,'home',3,'10-12/side','45 sec',NULL,
 3,2,'low','["triceps"]','isolation_elbow_extension',
 1,1,0,'Lighter dumbbell.','Heavier dumbbell or pause at lockout.',
 '["kickback","triceps","isolation"]','expert_consensus'),

(957,'Diamond Push-Up','diamond-push-up',
 'Bodyweight close-stance push-up with hands forming a diamond — triceps and inner-chest bias.',
 'In a push-up position place hands close so thumbs and index fingers touch, forming a diamond. Lower chest to the hands, press up.',
 '["elbows close to body","do not flare","full ROM"]',
 'intermediate','strength','sagittal','phosphagen','concentric',
 0,1,'home',3,'8-15','60 sec',NULL,
 4,3,'moderate','["triceps","chest"]','press_bilateral_bodyweight',
 1,1,0,'Knee diamond push-up.','Decline diamond push-up.',
 '["diamond push up","triceps","bodyweight"]','expert_consensus'),

-- ===== SHOULDERS (ISOLATION) =====
(958,'Cable Lateral Raise','cable-lateral-raise',
 'Single-arm cable lateral raise — constant-tension lateral-delt work.',
 'Stand sideways to a low cable, handle in the outside hand. Raise arm out to the side to shoulder height, lower under tension.',
 '["lead with elbow","stop at shoulder height","slow eccentric"]',
 'beginner','strength','frontal','glycolytic','concentric',
 1,0,'gym',3,'12-15/side','45 sec',NULL,
 3,2,'low','["delt_lateral"]','isolation_lateral_raise',
 1,1,0,'Lighter cable or banded raise.','Heavier load or higher rep myo-reps.',
 '["lateral raise","cable","shoulders"]','expert_consensus'),

(959,'Dumbbell Front Raise','dumbbell-front-raise',
 'Dumbbell front raise — anterior-delt isolation.',
 'Stand with dumbbells in front of thighs. Raise one or both dumbbells to shoulder height with straight arms, lower under control.',
 '["raise to shoulder height","no torso swing","slow eccentric"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'12-15','45 sec',NULL,
 3,2,'low','["delt_anterior"]','isolation_front_raise',
 1,1,0,'Lighter dumbbells or single-arm.','Heavier dumbbells or plate raise.',
 '["front raise","dumbbell","anterior delt"]','expert_consensus'),

(960,'Cable Reverse Fly','cable-reverse-fly',
 'Standing cable reverse fly with cables crossed — rear-delt isolation with constant tension.',
 'Stand at a dual cable station, cables crossed (right hand grabs left cable and vice versa). Pull arms out to the sides at shoulder height, squeezing rear delts.',
 '["pull from rear delts","squeeze shoulder blades","control return"]',
 'beginner','strength','transverse','glycolytic','concentric',
 0,0,'gym',3,'12-15','45 sec',NULL,
 3,2,'low','["delt_posterior","rhomboids"]','isolation_reverse_fly',
 1,1,1,'Banded reverse fly.','Heavier cable load.',
 '["cable reverse fly","rear delt","cable"]','expert_consensus'),

(961,'Rear Delt Pec Deck','rear-delt-pec-deck',
 'Reverse pec-deck machine — fixed-path rear delt isolation.',
 'Sit facing the pec deck with handles set for reverse use. Drive elbows back, squeezing rear delts. Control the return.',
 '["lead with elbows","do not shrug","squeeze rear delts"]',
 'beginner','strength','transverse','glycolytic','concentric',
 0,0,'gym',3,'12-15','45 sec',NULL,
 3,2,'low','["delt_posterior","rhomboids"]','isolation_reverse_fly',
 1,1,1,'Lighter load.','Heavier load.',
 '["rear delt fly","pec deck reverse","machine"]','expert_consensus'),

(962,'Upright Row (Barbell)','upright-row-barbell',
 'Barbell upright row — traps and lateral-delt work; shoulder-position aware.',
 'Stand with barbell at hip-width grip. Pull the bar up the body to mid-chest, elbows leading high. Lower with control. Stop short of shoulder pain.',
 '["elbows lead","stop if shoulder pinches","narrow but not too narrow"]',
 'intermediate','strength','frontal','glycolytic','concentric',
 0,0,'gym',3,'10-12','60 sec',NULL,
 4,3,'moderate','["traps","delt_lateral"]','isolation_upright_row',
 0,0,0,'Cable or DB upright row to shoulder height.','Heavier load.',
 '["upright row","barbell","traps"]','expert_consensus'),

-- ===== TRAPS =====
(963,'Barbell Shrug','barbell-shrug',
 'Standing barbell shrug — upper-trap isolation.',
 'Hold a barbell at thigh height (or rack pin). Shrug shoulders straight up toward ears, squeeze, lower under control.',
 '["pure vertical shrug","do not roll shoulders","squeeze hard at top"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 3,2,'moderate','["upper_traps"]','isolation_shrug',
 1,1,0,'Dumbbell shrug.','Heavier load or longer hold at top.',
 '["barbell shrug","traps","isolation"]','expert_consensus'),

(964,'Dumbbell Shrug','dumbbell-shrug',
 'Dumbbell shrug — upper-trap isolation with neutral-grip dumbbells.',
 'Hold heavy dumbbells at the sides. Shrug shoulders straight up, squeeze, lower with control.',
 '["pure vertical shrug","squeeze 1s at top","no neck strain"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'10-15','60 sec',NULL,
 3,2,'moderate','["upper_traps"]','isolation_shrug',
 1,1,0,'Lighter dumbbells.','Heavier load.',
 '["dumbbell shrug","traps","isolation"]','expert_consensus'),

-- ===== CHEST (ISOLATION) =====
(965,'Dumbbell Fly (Flat)','dumbbell-fly-flat',
 'Flat-bench dumbbell fly — chest stretch and adduction work.',
 'Lie on a flat bench with dumbbells over the chest, palms facing in, slight elbow bend. Lower the dumbbells out in an arc until you feel a chest stretch. Bring them back together by squeezing the chest.',
 '["soft elbow bend","feel chest stretch","arc not press"]',
 'intermediate','strength','transverse','glycolytic','concentric',
 0,0,'home',3,'10-12','60 sec',NULL,
 4,3,'moderate','["chest"]','isolation_fly',
 1,1,0,'Lighter dumbbells.','Heavier load or incline fly.',
 '["fly","dumbbell","chest","isolation"]','expert_consensus'),

(966,'Incline Dumbbell Fly','incline-dumbbell-fly',
 'Incline dumbbell fly — upper-chest stretch and adduction.',
 'Set bench to 30-45°. Hold dumbbells over the chest with a slight elbow bend. Lower the dumbbells out in an arc, then squeeze them back together.',
 '["soft elbow bend","upper chest stretch","arc not press"]',
 'intermediate','strength','transverse','glycolytic','concentric',
 0,0,'home',3,'10-12','60 sec',NULL,
 4,3,'moderate','["chest"]','isolation_fly',
 1,1,0,'Lighter dumbbells.','Heavier load.',
 '["incline fly","dumbbell","chest"]','expert_consensus'),

(967,'Pec Deck Fly','pec-deck-fly',
 'Pec deck machine — fixed-path chest fly with controlled stretch and squeeze.',
 'Sit at the pec-deck machine with forearms or hands on the pads. Bring the pads together by squeezing the chest. Control the return.',
 '["lead with elbows","squeeze the chest","control eccentric"]',
 'beginner','strength','transverse','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 3,2,'moderate','["chest"]','isolation_fly',
 1,1,0,'Lighter load.','Heavier load.',
 '["pec deck","chest fly","machine"]','expert_consensus'),

-- ===== CORE (CANONICAL) =====
(968,'Crunch','crunch',
 'Floor crunch — rectus abdominis isolation, short-range trunk flexion.',
 'Lie on back, knees bent, feet flat. Hands at temples (not pulling the neck). Curl the upper torso off the floor, exhale at the top. Lower with control.',
 '["chin off the chest","ribs to hips","exhale at top"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'15-25','30 sec',NULL,
 2,1,'low','["rectus_abdominis"]','isolation_trunk_flexion',
 1,1,0,'Pelvic tilt.','Cable crunch or weighted crunch.',
 '["crunch","abs","core"]','expert_consensus'),

(969,'Sit-Up','sit-up',
 'Bodyweight sit-up — full trunk flexion with hip-flexor involvement.',
 'Lie on back, knees bent, feet flat or anchored. Sit up by curling the spine off the floor until torso is vertical, lower under control.',
 '["roll up vertebra by vertebra","do not yank the neck","exhale on the way up"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'15-25','45 sec',NULL,
 3,2,'low','["rectus_abdominis","hip_flexors"]','isolation_trunk_flexion',
 1,1,0,'Crunch.','Decline sit-up or weighted sit-up.',
 '["sit up","abs","core"]','expert_consensus'),

(970,'Russian Twist','russian-twist',
 'Seated rotational twist — oblique work with optional weight.',
 'Sit on the floor, knees bent, lean torso back to ~45°. Hold weight at chest (or bodyweight). Rotate torso side to side, touching weight toward each hip.',
 '["rotate from the torso","stay tall","control speed"]',
 'beginner','strength','transverse','glycolytic','concentric',
 0,0,'home',3,'10-15/side','45 sec',NULL,
 3,2,'low','["obliques","rectus_abdominis"]','isolation_rotation',
 1,1,0,'Feet on floor.','Feet elevated or weighted.',
 '["russian twist","obliques","rotation"]','expert_consensus'),

(971,'Bicycle Crunch','bicycle-crunch',
 'Alternating elbow-to-knee crunch with leg cycling — combined flexion and rotation.',
 'Lie on back, hands at temples. Bring one knee toward the chest while rotating the opposite elbow to meet it. Alternate sides in a smooth cycling motion.',
 '["rotate from the torso","do not yank the neck","slow and controlled"]',
 'beginner','strength','transverse','glycolytic','concentric',
 0,0,'home',3,'10-15/side','45 sec',NULL,
 3,2,'low','["rectus_abdominis","obliques"]','isolation_rotation',
 1,1,0,'Slow tempo with feet down.','Weighted or longer set.',
 '["bicycle crunch","obliques","core"]','expert_consensus'),

(972,'V-Up','v-up',
 'V-up — simultaneous trunk and hip flexion meeting in a V shape.',
 'Lie flat on back, arms overhead. Simultaneously raise legs and torso to meet over the hips, reaching hands toward feet. Lower with control.',
 '["legs and torso move together","slow and controlled","do not slam down"]',
 'intermediate','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'8-12','60 sec',NULL,
 4,3,'moderate','["rectus_abdominis","hip_flexors"]','isolation_trunk_flexion',
 0,1,0,'Tuck-up.','Weighted V-up or pike compression.',
 '["v-up","abs","core"]','expert_consensus'),

(973,'Cable Crunch','cable-crunch',
 'Kneeling cable crunch — heavy weighted spinal flexion for the rectus abdominis.',
 'Kneel facing a high cable with rope attachment, rope behind/over the shoulders. Curl the torso down toward the floor by flexing the spine. Return under control.',
 '["round the spine","do not hinge at the hips","squeeze abs at bottom"]',
 'intermediate','strength','sagittal','glycolytic','concentric',
 0,0,'gym',3,'10-15','60 sec',NULL,
 4,3,'moderate','["rectus_abdominis"]','isolation_trunk_flexion',
 1,1,0,'Bodyweight crunch.','Heavier cable load or paused reps.',
 '["cable crunch","abs","weighted core"]','expert_consensus'),

(974,'Front Plank','front-plank',
 'Standard prone plank — anti-extension core endurance.',
 'Forearms on the floor, elbows under shoulders, body in a straight line. Brace through the core, glutes, and quads. Hold the position.',
 '["ribs over pelvis","squeeze glutes","do not sag"]',
 'beginner','strength','sagittal','glycolytic','isometric',
 0,1,'home',3,'30-60 sec','30 sec',NULL,
 2,1,'low','["core","rectus_abdominis","transverse_abdominis"]','isolation_anti_extension',
 1,1,1,'Knee plank.','Long-arm plank or weighted plank.',
 '["plank","core","endurance"]','expert_consensus'),

(975,'Reverse Crunch','reverse-crunch',
 'Lying reverse crunch — lower-rectus emphasis via posterior pelvic tilt.',
 'Lie on back, hands at sides or under hips. Bring knees toward chest by curling the pelvis off the floor. Lower with control.',
 '["roll the hips up","do not swing the legs","slow eccentric"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,0,'home',3,'10-15','45 sec',NULL,
 3,2,'low','["rectus_abdominis","hip_flexors"]','isolation_trunk_flexion',
 1,1,0,'Bent-knee pelvic tilt.','Hanging reverse crunch.',
 '["reverse crunch","abs","core"]','expert_consensus'),

(976,'Hanging Knee Raise','hanging-knee-raise',
 'Hanging from a pull-up bar, raise knees to hip height — core and hip-flexor work.',
 'Hang from a pull-up bar with arms straight. Raise knees toward the chest by flexing hips and lower abs. Lower under control without swinging.',
 '["no swinging","squeeze at the top","slow descent"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 0,1,'gym',3,'10-15','60 sec',NULL,
 4,3,'moderate','["rectus_abdominis","hip_flexors","grip"]','isolation_trunk_flexion',
 0,1,0,'Captain''s chair knee raise.','Toes-to-bar or weighted knee raise.',
 '["knee raise","hanging","core"]','expert_consensus'),

-- (Dead Bug id 109 and Bird Dog id 110 already exist in DB as prehab; not adding.)

-- ===== FOREARM/GRIP =====
(979,'Wrist Curl (Dumbbell)','wrist-curl-dumbbell',
 'Seated dumbbell wrist curl — forearm-flexor strengthening, palms-up.',
 'Sit with forearm on thigh, palm up, dumbbell in hand. Let the wrist drop, then curl the weight up by flexing the wrist. Lower under control.',
 '["full ROM","slow tempo","palms up"]',
 'beginner','strength','sagittal','glycolytic','concentric',
 1,0,'home',3,'12-15/side','45 sec',NULL,
 2,1,'low','["forearm_flexors"]','isolation_wrist',
 1,1,0,'Lighter dumbbell.','Heavier dumbbell or barbell wrist curl.',
 '["wrist curl","forearm","grip"]','expert_consensus');

COMMIT;

-- ============================================================================
-- Muscle-group links (primary/secondary)
-- ============================================================================
BEGIN TRANSACTION;

INSERT INTO exercise_muscles (exercise_id, muscle_group_id, role) VALUES
-- 900 Barbell Bench Press
(900,12,'primary'),(900,39,'secondary'),(900,16,'secondary'),(900,14,'stabilizer'),
-- 901 Incline BB Bench
(901,11,'primary'),(901,16,'secondary'),(901,39,'secondary'),
-- 902 Close-Grip Bench
(902,39,'primary'),(902,10,'secondary'),(902,16,'secondary'),
-- 903 Floor Press
(903,39,'primary'),(903,10,'secondary'),(903,16,'secondary'),
-- 904 BB OHP
(904,15,'primary'),(904,16,'primary'),(904,39,'secondary'),(904,3,'stabilizer'),
-- 905 Push Press
(905,15,'primary'),(905,16,'primary'),(905,39,'secondary'),(905,65,'secondary'),
-- 906 Push Jerk
(906,15,'primary'),(906,16,'primary'),(906,65,'secondary'),(906,39,'secondary'),
-- 907 Incline DB Bench
(907,11,'primary'),(907,16,'secondary'),(907,39,'secondary'),
-- 908 Seated DB Press
(908,15,'primary'),(908,16,'primary'),(908,39,'secondary'),
-- 909 Arnold Press
(909,15,'primary'),(909,16,'primary'),(909,39,'secondary'),
-- 910 Hang Clean
(910,74,'primary'),(910,70,'primary'),(910,65,'secondary'),(910,27,'secondary'),
-- 911 Clean Pull
(911,74,'primary'),(911,70,'primary'),(911,27,'secondary'),(911,54,'secondary'),
-- 912 Power Snatch
(912,74,'primary'),(912,70,'primary'),(912,27,'secondary'),(912,15,'secondary'),
-- 913 Snatch Pull
(913,74,'primary'),(913,70,'primary'),(913,27,'secondary'),
-- 914 Clean & Jerk
(914,74,'primary'),(914,70,'primary'),(914,15,'primary'),(914,65,'secondary'),
-- 915 Snatch
(915,74,'primary'),(915,70,'primary'),(915,15,'primary'),(915,65,'secondary'),
-- 916 Sumo Deadlift
(916,74,'primary'),(916,70,'primary'),(916,82,'secondary'),(916,42,'secondary'),
-- 917 Stiff-Leg Deadlift
(917,70,'primary'),(917,54,'primary'),(917,74,'secondary'),
-- 918 Deficit Deadlift
(918,74,'primary'),(918,70,'primary'),(918,65,'secondary'),(918,42,'secondary'),
-- 919 Pause Squat
(919,65,'primary'),(919,74,'primary'),(919,70,'secondary'),(919,3,'stabilizer'),
-- 920 Box Squat
(920,65,'primary'),(920,74,'primary'),(920,70,'secondary'),
-- 921 Good Morning
(921,70,'primary'),(921,54,'primary'),(921,74,'secondary'),
-- 922 Pull-Up
(922,26,'primary'),(922,36,'secondary'),(922,42,'stabilizer'),
-- 923 Chin-Up
(923,26,'primary'),(923,36,'primary'),(923,42,'stabilizer'),
-- 924 Neutral-Grip Pull-Up
(924,26,'primary'),(924,36,'secondary'),(924,37,'secondary'),
-- 925 Lat Pulldown Wide
(925,26,'primary'),(925,36,'secondary'),(925,29,'secondary'),
-- 926 T-Bar Row
(926,26,'primary'),(926,29,'primary'),(926,31,'secondary'),(926,36,'secondary'),
-- 927 Pendlay Row
(927,26,'primary'),(927,29,'primary'),(927,54,'stabilizer'),
-- 928 Meadows Row
(928,26,'primary'),(928,29,'primary'),(928,36,'secondary'),
-- 929 Seal Row
(929,26,'primary'),(929,29,'primary'),(929,31,'secondary'),
-- 930 Machine Row
(930,26,'primary'),(930,29,'primary'),(930,31,'secondary'),(930,36,'secondary'),
-- 931 Leg Press
(931,65,'primary'),(931,74,'secondary'),(931,82,'secondary'),
-- 932 Hack Squat
(932,65,'primary'),(932,74,'secondary'),
-- 933 Leg Extension
(933,65,'primary'),(933,66,'primary'),
-- 934 Lying Leg Curl
(934,70,'primary'),
-- 935 Seated Leg Curl
(935,70,'primary'),
-- 936 Hip Abduction
(936,76,'primary'),(936,74,'secondary'),
-- 937 Hip Adduction
(937,82,'primary'),
-- 938 Cable Pull-Through
(938,74,'primary'),(938,70,'primary'),
-- 939 45° Back Extension
(939,74,'primary'),(939,54,'primary'),(939,70,'secondary'),
-- 940 Reverse Hyper
(940,74,'primary'),(940,70,'primary'),(940,54,'secondary'),
-- 941 GHR
(941,70,'primary'),(941,74,'secondary'),(941,54,'secondary'),
-- 942 Seated Calf Raise
(942,85,'primary'),(942,83,'secondary'),
-- 943 Walking Lunge
(943,65,'primary'),(943,74,'primary'),(943,82,'secondary'),
-- 944 Reverse Lunge BB
(944,65,'primary'),(944,74,'primary'),
-- 945 Forward Lunge DB
(945,65,'primary'),(945,74,'primary'),
-- 946 Barbell Curl
(946,36,'primary'),(946,37,'secondary'),
-- 947 EZ-Bar Curl
(947,36,'primary'),(947,37,'secondary'),
-- 948 Dumbbell Curl
(948,36,'primary'),(948,37,'secondary'),
-- 949 Incline DB Curl
(949,36,'primary'),(949,37,'secondary'),
-- 950 Hammer Curl
(950,37,'primary'),(950,38,'primary'),(950,36,'secondary'),
-- 951 Concentration Curl
(951,36,'primary'),
-- 952 Cable Curl
(952,36,'primary'),(952,37,'secondary'),
-- 953 Tricep Pushdown
(953,39,'primary'),
-- 954 Rope Pushdown
(954,39,'primary'),
-- 955 Overhead Cable Tri Ext
(955,39,'primary'),
-- 956 Tricep Kickback
(956,39,'primary'),
-- 957 Diamond Push-Up
(957,39,'primary'),(957,10,'secondary'),
-- 958 Cable Lateral Raise
(958,17,'primary'),
-- 959 DB Front Raise
(959,16,'primary'),
-- 960 Cable Reverse Fly
(960,18,'primary'),(960,31,'secondary'),
-- 961 Rear Delt Pec Deck
(961,18,'primary'),(961,31,'secondary'),
-- 962 Upright Row BB
(962,28,'primary'),(962,17,'secondary'),
-- 963 Barbell Shrug
(963,28,'primary'),
-- 964 Dumbbell Shrug
(964,28,'primary'),
-- 965 DB Fly Flat
(965,12,'primary'),(965,10,'secondary'),
-- 966 Incline DB Fly
(966,11,'primary'),(966,10,'secondary'),
-- 967 Pec Deck Fly
(967,10,'primary'),
-- 968 Crunch
(968,50,'primary'),
-- 969 Sit-Up
(969,50,'primary'),(969,78,'secondary'),
-- 970 Russian Twist
(970,51,'primary'),(970,50,'secondary'),
-- 971 Bicycle Crunch
(971,50,'primary'),(971,51,'primary'),
-- 972 V-Up
(972,50,'primary'),(972,78,'secondary'),
-- 973 Cable Crunch
(973,50,'primary'),
-- 974 Front Plank
(974,3,'primary'),(974,50,'primary'),(974,53,'primary'),
-- 975 Reverse Crunch
(975,50,'primary'),(975,78,'secondary'),
-- 976 Hanging Knee Raise
(976,50,'primary'),(976,78,'primary'),(976,42,'stabilizer'),
-- 979 Wrist Curl
(979,40,'primary');

COMMIT;

-- ============================================================================
-- Equipment links
-- ============================================================================
BEGIN TRANSACTION;

INSERT INTO exercise_equipment (exercise_id, equipment_id, is_required) VALUES
(900,10,1),(900,95,1),(900,97,1),
(901,10,1),(901,96,1),(901,97,1),
(902,10,1),(902,95,1),(902,97,1),
(903,10,1),(903,97,1),
(904,10,1),(904,97,1),
(905,10,1),(905,97,1),
(906,10,1),(906,97,1),
(907,11,1),(907,96,1),
(908,11,1),(908,96,1),
(909,11,1),(909,96,1),
(910,10,1),(910,97,1),
(911,10,1),(911,97,1),
(912,10,1),(912,97,1),
(913,10,1),(913,97,1),
(914,10,1),(914,97,1),
(915,10,1),(915,97,1),
(916,10,1),(916,97,1),
(917,10,1),(917,97,1),
(918,10,1),(918,17,1),(918,97,1),
(919,10,1),(919,97,1),
(920,10,1),(920,97,1),
(921,10,1),(921,97,1),
(922,2,1),
(923,2,1),
(924,2,1),
(925,88,1),
(926,10,1),(926,17,1),
(927,10,1),
(928,10,1),
(929,11,1),(929,95,1),
(930,1,1),
(931,85,1),
(932,93,1),
(933,87,1),
(934,86,1),
(935,86,1),
(936,92,1),
(937,92,1),
(938,24,1),
(939,90,1),
(940,91,1),
(941,90,1),
(942,1,1),
(943,11,1),
(944,10,1),(944,97,1),
(945,11,1),
(946,10,1),
(947,10,1),
(948,11,1),
(949,11,1),(949,96,1),
(950,11,1),
(951,11,1),(951,95,1),
(952,24,1),
(953,24,1),
(954,24,1),
(955,24,1),
(956,11,1),(956,95,1),
(957,1,1),
(958,24,1),
(959,11,1),
(960,24,1),
(961,89,1),
(962,10,1),
(963,10,1),
(964,11,1),
(965,11,1),(965,95,1),
(966,11,1),(966,96,1),
(967,89,1),
(968,1,1),
(969,1,1),
(970,1,1),
(971,1,1),
(972,1,1),
(973,24,1),
(974,1,1),
(975,1,1),
(976,2,1),
(979,11,1);

COMMIT;
