// MuscleChipBadge.swift — 28pt outer / 24pt inner anatomy badge.
//
// Used as the bottom-right cap of `CompositeLeading` (photo + chip badge
// composite leading slot on `.presentation` tiles). The 28pt artwork is a
// pre-rendered template PNG bundled in Assets.xcassets/MuscleChips/ —
// generated by MuscleChipGeneratorView (DEBUG-only) so we don't pay for
// MuscleMap's ForEach-of-shape-paths on every scrolling row, and so the
// bucket-specific highlight is actually visible at chip scale (the live
// BodyAnatomyView blurs to a uniform silhouette below ~80pt).
//
// The image is template-rendered: `Color.accent` tints the opaque silhouette
// pixels uniformly, with the bucket's primary muscle drawn fully opaque and
// the surrounding body at partial alpha, so the chip remains visually
// distinct bucket-to-bucket at 28pt.
//
// If the bundled asset is missing for some reason, we fall back to the live
// BodyAnatomyView (unreachable on a clean build, but keeps the chip
// rendering correctly during asset-regeneration iterations).

import SwiftUI
import UIKit

struct MuscleChipBadge: View {
    let group: MuscleBucket
    let side: BodyAnatomyView.AnatomySide

    var body: some View {
        RoundedRectangle(cornerRadius: 6)
            .fill(Color.bg)
            .frame(width: 28, height: 28)
            .overlay {
                ZStack {
                    RoundedRectangle(cornerRadius: 4)
                        .fill(Color.elevated)
                    chipArtwork
                        .padding(2)
                }
                .padding(2)
            }
            .accessibilityHidden(true)
    }

    private var assetName: String {
        "MuscleChips/\(group.rawValue)-\(side == .front ? "front" : "back")"
    }

    @ViewBuilder
    private var chipArtwork: some View {
        if UIImage(named: assetName) != nil {
            Image(assetName)
                .renderingMode(.template)
                .resizable()
                .scaledToFit()
                .foregroundStyle(Color.accent)
        } else {
            // Fallback: live BodyAnatomyView. Unreachable when the bundled
            // assets are present, but keeps the chip rendering correctly if
            // an imageset is missing during regeneration iterations.
            BodyAnatomyView(
                highlights: [group.primarySlug: .primary],
                side: side,
                tint: Color.accent
            )
        }
    }
}

// MARK: - Preview

#Preview("All buckets × front/back") {
    ScrollView {
        VStack(alignment: .leading, spacing: 16) {
            ForEach(MuscleBucket.allCases) { bucket in
                HStack(spacing: 12) {
                    Text(bucket.label)
                        .font(.custom("Inter-Regular", size: 13))
                        .foregroundStyle(Color.ink2)
                        .frame(width: 100, alignment: .leading)
                    MuscleChipBadge(group: bucket, side: .front)
                    MuscleChipBadge(group: bucket, side: .back)
                    Text("natural: \(bucket.naturalSide == .front ? "front" : "back")")
                        .font(.monoXS)
                        .foregroundStyle(Color.ink3)
                }
            }
        }
        .padding(20)
    }
    .background(Color.bg.ignoresSafeArea())
    .preferredColorScheme(.dark)
}
