#!/usr/bin/env bash
#
# generate-coach-secrets.sh — emit PhaseTraining/Generated/CoachSecrets.swift
# with the Cloudflare AI Gateway token for the current build configuration.
#
# Run by Xcode as a pre-build phase (see Project.yml preBuildScripts). Token
# source resolution:
#   1. ~/.config/phase-training/cf-aigateway-tokens.env (local dev)
#   2. Process env vars (CI: GH Actions sets these from secrets)
#      - PHASETRAINING_CF_AIG_DEV_TOKEN
#      - PHASETRAINING_CF_AIG_PROD_TOKEN
#
# Configuration → token mapping:
#   Debug   → PHASETRAINING_CF_AIG_DEV_TOKEN
#   Release → PHASETRAINING_CF_AIG_PROD_TOKEN
#
# If no token is found, writes an empty string and a clear marker comment.
# The build succeeds; CoachClient surfaces "no gateway token configured" at
# runtime when the user toggles the coach on.
#
# Idempotent — only writes the file when its contents would change. Avoids
# triggering Xcode incremental-rebuild churn on every clean build.

set -euo pipefail

# When Xcode runs us as a build phase, $SRCROOT is the project dir. When run
# from CLI for dev/test, fall back to repo-relative path.
SRC_DIR="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT_DIR="$SRC_DIR/PhaseTraining/Generated"
OUT_FILE="$OUT_DIR/CoachSecrets.swift"
ENV_FILE="$HOME/.config/phase-training/cf-aigateway-tokens.env"

# 1. Source the local env file if present (lets `make build` etc. pick it up
#    without exporting first).
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
fi

# 2. Pick the right token for this configuration. CONFIGURATION is set by
#    Xcode build phases; default to Debug for ad-hoc CLI runs.
CONFIG="${CONFIGURATION:-Debug}"
case "$CONFIG" in
  Debug)   TOKEN="${PHASETRAINING_CF_AIG_DEV_TOKEN:-}" ;;
  Release) TOKEN="${PHASETRAINING_CF_AIG_PROD_TOKEN:-}" ;;
  *)       TOKEN="" ;;
esac

# 2b. BETA BUILDS SHIP NO TOKEN.
#
# A distributed IPA carries whatever string we bake in, and the Cloudflare
# gateway is BYOK: anyone who runs `strings` on a build a tester received gets
# an unmetered Claude proxy billed to us, bounded only by a client-side
# UserDefaults counter they can also bypass. Handing builds to external testers
# is exactly when that stops being theoretical.
#
# PHASETRAINING_BETA=1 blanks the token HERE, at generation, so it never
# reaches the binary at all. Gating in Swift would not be enough: the literal
# would still be in the compiled string table.
#
# CoachClient already refuses to send on an empty token, and
# CoachEntitlement.coachAvailable hides the surfaces, so the app degrades to
# "coach not in this build" rather than erroring at the user.
if [ "${PHASETRAINING_BETA:-0}" = "1" ]; then
  TOKEN=""
  BETA_NOTE=" (beta build — token withheld on purpose)"
else
  BETA_NOTE=""
fi

mkdir -p "$OUT_DIR"

# Mark missing token with an empty value + a comment so runtime can detect.
if [ -z "$TOKEN" ]; then
  MARKER="// WARNING: no token resolved for configuration $CONFIG$BETA_NOTE"
else
  MARKER="// Token resolved for configuration $CONFIG"
fi

NEW_CONTENT=$(cat <<EOF
// CoachSecrets.swift — GENERATED by scripts/generate-coach-secrets.sh.
// Do not edit by hand. Do not check into git. Regenerated each build from
// ~/.config/phase-training/cf-aigateway-tokens.env or process env vars.
$MARKER

import Foundation

enum CoachSecrets {
    /// Cloudflare AI Gateway authenticated-gateway token. Empty string means
    /// no token was resolved at build time — CoachClient must refuse to send
    /// requests in that state.
    static let gatewayToken: String = "$TOKEN"
}
EOF
)

# Idempotent write — skip if unchanged.
if [ -f "$OUT_FILE" ] && [ "$(cat "$OUT_FILE")" = "$NEW_CONTENT" ]; then
  echo "CoachSecrets.swift unchanged for $CONFIG"
  exit 0
fi

echo "$NEW_CONTENT" > "$OUT_FILE"
echo "Wrote $OUT_FILE for configuration $CONFIG (token present: $([ -n "$TOKEN" ] && echo yes || echo no))"
