#!/usr/bin/env bash
#
# install_muscle_chips.sh — copy the 22 muscle-chip PNGs generated by
# MuscleChipGeneratorView (DEBUG-only screen in the app) out of the sim's
# Documents directory and into Assets.xcassets/MuscleChips/<bucket>-<side>.imageset/,
# writing the Contents.json each imageset needs for template rendering.
#
# Workflow:
#   1. Build + launch PhaseTraining in the simulator with
#      `--ui-test-onboarded --regenerate-muscle-chips` so the generator
#      sheet auto-presents and the rendering kicks off automatically.
#   2. Wait ~5–10s for all 22 × 3 = 66 PNGs to land in Documents/MuscleChips.
#   3. Run this script. It locates the app's Documents dir via
#      `xcrun simctl get_app_container`, copies the per-scale PNGs into the
#      right imageset folders, and emits a Contents.json for each.
#
# Re-runnable: deletes + recreates the MuscleChips/ catalog folder each run
# so stale assets can't linger.

set -euo pipefail

BUNDLE_ID="${BUNDLE_ID:-com.phasetraining.app}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS_DIR="${REPO_ROOT}/PhaseTraining/Resources/Assets.xcassets/MuscleChips"

# Pick a booted simulator. Default to the first one; override with SIM_UDID.
if [[ -z "${SIM_UDID:-}" ]]; then
  SIM_UDID="$(xcrun simctl list devices booted -j \
    | python3 -c 'import json,sys
data=json.load(sys.stdin)
for runtime, devs in data["devices"].items():
    for d in devs:
        if d.get("state")=="Booted":
            print(d["udid"]); sys.exit(0)
sys.exit("no booted simulator found")')"
fi
echo "Using simulator: ${SIM_UDID}"

APP_DATA="$(xcrun simctl get_app_container "${SIM_UDID}" "${BUNDLE_ID}" data)"
SRC_DIR="${APP_DATA}/Documents/MuscleChips"

if [[ ! -d "${SRC_DIR}" ]]; then
  echo "ERROR: ${SRC_DIR} does not exist. Run the app with --regenerate-muscle-chips first." >&2
  exit 1
fi

BUCKETS=(chest back shoulders biceps triceps forearms quads hamstrings glutes calves core)
SIDES=(front back)

echo "Resetting ${ASSETS_DIR}/"
rm -rf "${ASSETS_DIR}"
mkdir -p "${ASSETS_DIR}"

# Write the catalog-folder Contents.json so Xcode treats MuscleChips/ as a
# folder reference inside the asset catalog (provides-namespace makes the
# images live in the "MuscleChips/" namespace at runtime).
cat > "${ASSETS_DIR}/Contents.json" <<'EOF'
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  },
  "properties" : {
    "provides-namespace" : true
  }
}
EOF

count=0
missing=()
for bucket in "${BUCKETS[@]}"; do
  for side in "${SIDES[@]}"; do
    name="${bucket}-${side}"
    imageset_dir="${ASSETS_DIR}/${name}.imageset"
    mkdir -p "${imageset_dir}"

    found_any=0
    for scale in 1 2 3; do
      src="${SRC_DIR}/${name}@${scale}x.png"
      dst="${imageset_dir}/${name}@${scale}x.png"
      if [[ -f "${src}" ]]; then
        cp "${src}" "${dst}"
        found_any=1
      else
        missing+=("${src}")
      fi
    done

    cat > "${imageset_dir}/Contents.json" <<EOF
{
  "images" : [
    {
      "filename" : "${name}@1x.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "filename" : "${name}@2x.png",
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "filename" : "${name}@3x.png",
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  },
  "properties" : {
    "template-rendering-intent" : "template"
  }
}
EOF

    if [[ ${found_any} -eq 1 ]]; then
      count=$((count + 1))
    fi
  done
done

echo "Wrote ${count} imageset(s) to ${ASSETS_DIR}"
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "WARNING: missing source files (${#missing[@]}):" >&2
  printf '  %s\n' "${missing[@]}" >&2
  exit 1
fi
